:arrow_up::one::four: ir_attachment_url: fix tests
itpp-labs/misc-addons pull request #1053
Opened 2020-12-21 12:27 UTC by yelizariev

WHY: image field was removed from res.country: https://github.com/odoo/odoo/commit/710705b64c0134a5b568d998d0a3eb0df0f541c0

2020-12-25 07:02 UTC, trojikman requested changes

2020-12-25 07:02 UTC, trojikman commented on ir_attachment_url/doc/index.rst
> +* RESULT: you will see that the avatar of the user has been changed to that pasted picture
I can't get that result

2020-12-26 15:53 UTC, yelizariev commented on ir_attachment_url/doc/index.rst
> +* RESULT: you will see that the avatar of the user has been changed to that pasted picture
fixed

2020-12-28 14:14 UTC, trojikman approved these changes

2020-12-28 14:14 UTC, merged