14.0 ir attachment s3
itpp-labs/misc-addons pull request #1066
Opened 2021-01-03 18:32 UTC by yelizariev

2021-01-03 18:35 UTC, yelizariev commented
Эти комиты можно потом в 13 перенести:

* update minio instructions 
* ir_attachment_{url|s3}: direct downloading

2021-01-11 17:47 UTC, trojikman approved these changes

2021-01-12 05:22 UTC, trojikman requested changes
по `ir_attachment_url` тесты сломались

2021-01-12 06:15 UTC, trojikman requested changes

2021-01-12 06:15 UTC, trojikman commented on ir_attachment_url/models/ir_attachment.py
> -                attach.datas = base64.b64encode(r.content)
@yelizariev Проверка, судя по всему не актуальна, просто удалить или переделать?
https://github.com/itpp-labs/misc-addons/blob/38c029b1552912b204927638b57160fa13ee8e2f/ir_attachment_url/tests/test_attachment_fields.py#L27

2021-01-12 08:07 UTC, yelizariev commented on ir_attachment_url/models/ir_attachment.py
> -                attach.datas = base64.b64encode(r.content)
Посмотрю. Вроде должно работать

2021-01-21 13:46 UTC, yelizariev commented
В тестах вот здесь атачменты не находит и соответственно значение не сохраняется

https://github.com/itpp-labs/misc-addons/blob/52d8aa91a45007bdc12559f7d3fd247f2e3e2c7c/ir_attachment_url/models/base.py#L37-L43

2021-01-21 13:49 UTC, yelizariev commented
Если откатится на этого комита, то работает
https://github.com/itpp-labs/misc-addons/pull/1066/commits/f63054270920f8d09811d7cce7acc70cf0deff8e

Значит после доп обновлений проблема возникает.

2021-01-21 13:51 UTC, yelizariev commented
Ошибка появляется на этом комите https://github.com/itpp-labs/misc-addons/pull/1066/commits/c805dc98749635e79e4f0961f81d34952ffba357

2021-01-24 10:15 UTC, yelizariev commented on ir_attachment_url/models/ir_attachment.py
> -                attach.datas = base64.b64encode(r.content)
Разобрался. Не до конца переделал просто

https://github.com/itpp-labs/misc-addons/compare/52d8aa91a45007bdc12559f7d3fd247f2e3e2c7c..e7a3a7bf0cb51bacd98149e27c70e500d2dbf58b

2021-03-17 17:30 UTC, trojikman commented
Проходился по шагам документации `ir_attachement_url` и заметил такое после установки ссылки для image_128, блок с картинкой совсем ушел. Шаги полностью такие же как в документации
![Screenshot from 2021-03-17 22-26-17](https://user-images.githubusercontent.com/23641186/111511066-2dd5b800-8770-11eb-93bf-9741283c8c05.png)
UPD: 
Это было и до этого ПР, не помню было ли такое, когда принимали `ir_attachment_url`

2021-03-18 11:26 UTC, trojikman commented
Не уверен ошибка ли это, но когда прохожу по шагам документации и меняю `image_128` для аватара пользователя в настройках профиля картинка становится такой вот точкой:
![Screenshot from 2021-03-17 22-32-56](https://user-images.githubusercontent.com/23641186/111618555-54dec900-8806-11eb-9048-1b29968fd1e0.png)

2021-03-23 07:07 UTC, trojikman commented
Tested with minio too, works well

2021-03-23 09:40 UTC, trojikman approved these changes

2021-03-23 09:40 UTC, merged

2021-04-11 12:18 UTC, yelizariev commented
Не воспроизводится. Может у тебя картинка не грузилась?

![image](https://user-images.githubusercontent.com/186131/114303865-89296a80-9ad0-11eb-9ec3-675c9f09e639.png)


> Проходился по шагам документации `ir_attachement_url` и заметил такое после установки ссылки для image_128, блок с картинкой совсем ушел. Шаги полностью такие же как в документации
> ![Screenshot from 2021-03-17 22-26-17](https://user-images.githubusercontent.com/23641186/111511066-2dd5b800-8770-11eb-93bf-9741283c8c05.png)
> UPD:
> Это было и до этого ПР, не помню было ли такое, когда принимали `ir_attachment_url`