12.0 docs
itpp-labs/misc-addons pull request #1097
Opened 2021-03-05 13:22 UTC by trojikman

2021-03-05 13:29 UTC, yelizariev commented on web_theme_kit/README.rst
> +It is tested that if you don't need functionality of the `access_settings_menu <https://apps.odoo.com/apps/modules/12.0/access_settings_menu/>`__ you can remove it from dependencies of the ``web_debr
Может лучше в web_debranding эту заметку отправить?

2021-03-05 14:00 UTC, trojikman commented on web_theme_kit/README.rst
> +It is tested that if you don't need functionality of the `access_settings_menu <https://apps.odoo.com/apps/modules/12.0/access_settings_menu/>`__ you can remove it from dependencies of the ``web_debr
Тоже размышлял об этом

2021-03-05 14:54 UTC, yelizariev requested changes

2021-03-05 14:54 UTC, yelizariev commented on web_debranding/README.rst
> +It is tested that if you don't need functionality of the `access_settings_menu <https://apps.odoo.com/apps/modules/12.0/access_settings_menu/>`__ you can remove it from dependencies of the ``web_debr
```suggestion
If you don't need functionality of the `access_settings_menu <https://apps.odoo.com/apps/modules/12.0/access_settings_menu/>`__ you can remove it from dependencies in manifest file
```

2021-03-07 18:45 UTC, trojikman commented
I approve to merge it now

2021-03-07 18:45 UTC, merged