[FIX] Fixes small and medium image for ir_attachment_url
itpp-labs/misc-addons pull request #413
Opened 2017-04-19 13:03 UTC by GabbasovDinar

2017-04-19 13:38 UTC, yelizariev requested changes

2017-04-19 13:38 UTC, yelizariev commented on ir_attachment_url/models/image.py
> +        vals.update({small_name: url})
make this update via calling original function if it's not url

2017-04-19 13:42 UTC, GabbasovDinar commented on ir_attachment_url/models/image.py
> +        vals.update({small_name: url})
@yelizariev This is an overridden function, How can I call the original function?

2017-04-20 07:05 UTC, yelizariev approved these changes
Ok

2017-04-20 12:35 UTC, merged