10.0 web debranding fixes
itpp-labs/misc-addons pull request #518
Opened 2017-12-20 12:07 UTC by KolushovAlexandr

2017-12-20 13:02 UTC, yelizariev requested changes

2017-12-20 13:02 UTC, yelizariev commented on web_debranding/README.rst
> +24. Hides Odoo e-commerce youtube video
Where? For a planner use more common description:

     Removes official videos in planner

2017-12-20 13:03 UTC, yelizariev requested changes

2017-12-20 13:03 UTC, yelizariev commented on web_debranding/views.xml
> +    <template id="website_planner" inherit_id="website_sale.website_planner" priority="2">
You cannot reference to website_sale, because that may not be installed

2017-12-20 13:04 UTC, yelizariev commented on web_debranding/views.xml
> +    <template id="website_planner" inherit_id="website_sale.website_planner" priority="2">
Use this approach instead: web_debranding/models/web_planner.py

2017-12-21 11:56 UTC, yelizariev requested changes

2017-12-21 11:56 UTC, yelizariev commented on web_debranding/models/mail_message.py
> +        if type(msg.subject) is unicode and 'application installed' in msg.subject:
Use more strict condition to prevent replacing in usual mails

2017-12-21 12:40 UTC, yelizariev requested changes

2017-12-21 12:40 UTC, yelizariev commented on web_debranding/models/mail_message.py
> +           'General announcements for all employees.' == msg.channel_ids.description and \
Don't trust to description. Use self.env.ref(...).id

2017-12-21 12:40 UTC, yelizariev commented on web_debranding/models/mail_message.py
> +           'application installed!' in msg.subject and \
Use endswith

2017-12-21 12:40 UTC, yelizariev commented on web_debranding/models/mail_message.py
> +           'general' == msg.channel_ids.name:
Don't trust to channel name. Use self.env.ref(...).id

2017-12-22 07:47 UTC, yelizariev commented
For squashed message:

```

[10.0][BACKPORT] replace documentation links

[FIX] Remove official videos in planner
[ADD] Replace "Odoo" in 'application installed' messages
[FIX] Remove Enterprise radio-buttons in Settings

```

2017-12-25 17:17 UTC, ilmir-k commented
For some reason it gives the error on runbot after login: 

```
Error: QWeb2: Template 'PlannerLauncher' not found

http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:2908
Traceback:
QWeb2.tools.exception@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:2908:7
._render@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:2953:92
.render@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:2949:146
Widget<.renderElement@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:3118:1068
Widget<.__widgetRenderAndInsert/<@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:3118:912
.Deferred/promise.then/</</<@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:547:678
jQuery.Callbacks/fire@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:541:281
jQuery.Callbacks/self.add@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:542:467
.Deferred/promise.then/</<@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:547:631
.each@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:370:758
.Deferred/promise.then/<@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:547:553
.Deferred@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:548:189
.Deferred/promise.then@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:547:518
Widget<.__widgetRenderAndInsert@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:3118:879
Widget<.prependTo@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:3118:214
SystrayMenu<.load_items/<@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/359-f959bf1/web.assets_backend.js:1966:703
_.forEach@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:12:558
SystrayMenu<.load_items@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/359-f959bf1/web.assets_backend.js:1966:565
SystrayMenu<.start@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/359-f959bf1/web.assets_backend.js:1966:288
OdooClass.extend/</prototype[name]</<@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:3015:556
.show_application@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/359-f959bf1/web.assets_backend.js:1721:1295
WebClient<.start/<@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/359-f959bf1/web.assets_backend.js:1717:1680
.Deferred/promise.then/</</<@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:547:678
jQuery.Callbacks/fire@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:548:31
jQuery.Callbacks/fire@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:541:281
jQuery.Callbacks/self.add@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:542:467
.Deferred/promise.then/</</<@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:547:753
jQuery.Callbacks/fire@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:548:31
jQuery.Callbacks/fire@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:548:31
jQuery.Callbacks/fire@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:548:31
jQuery.Callbacks/fire@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:548:31
jQuery.Callbacks/fire@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:548:31
loadJS/script.onreadystatechange@http://12444-518-9fa582-base.runbot.it-projects.info/web/content/353-6e774da/web.assets_common.js:3038:25

```

2018-01-09 09:39 UTC, KolushovAlexandr commented
@ilmir-k @Railia Runbot is green now

2018-01-10 13:28 UTC, Railia reviewed
YourWebsiteWithOdoo.com hasn't changed

2018-01-18 10:56 UTC, yelizariev reviewed
The fix shows that introducing is_code was a bad idea. We need to update that

2018-01-18 10:56 UTC, yelizariev commented on web_debranding/models/ir_translation.py
> +                    u'show any activity In ' + new_name, source, flags=re.IGNORECASE)
We need to remove ``is_code`` and always replace Odoo.  Otherwise we have to add ALL cases of usage word Odoo in views.

To remove that, we need to update the regexp, which handles cases ``odoo.define``, but we need to add  more:

*  ``odoo =``
*  ``odoo.SOME_VARIABLE =``

Examples of code where odoo should not be replaced:

2018-01-18 12:06 UTC, Railia requested changes
I will approve the changes after taking into account all comments @yelizariev

2018-01-23 06:09 UTC, yelizariev requested changes
Document it a bit more, please. We will need such details when we port to next version, for example

2018-01-23 06:09 UTC, yelizariev commented on web_debranding/models/ir_translation.py
> +    source = re.sub(r'\odoo(?!\.\S|\s?=\s?|\w|\[)\b', new_name, source, flags=re.IGNORECASE)
Update comment:

* list of exceptions
* links to the source with word ``odoo`` as a code

2018-01-24 08:34 UTC, yelizariev requested changes

2018-01-24 08:34 UTC, yelizariev commented on web_debranding/models/ir_translation.py
> +    # https://github.com/odoo/odoo/blob/cd48a806ac636806130efcf5c055f73758cb0902/addons/iap/static/src/js/iap_credit.js#L10
Wrong example. JS files are not passed through this method

2018-01-24 08:34 UTC, yelizariev commented on web_debranding/models/ir_translation.py
> +    # https://github.com/odoo/odoo/blob/11.0/addons/web/static/src/js/boot.js#L47
Wrong example. JS files are not passed through this method

2018-01-24 08:34 UTC, yelizariev commented on web_debranding/models/ir_translation.py
> +    # https://github.com/odoo/odoo/blob/11.0/addons/web_editor/static/src/js/backend/fields.js#L227
Wrong example. JS files are not passed through this method

2018-01-24 10:57 UTC, merged

2018-01-24 10:57 UTC, yelizariev commented
:+1: