10.0 fix ir attachment url avatar
itpp-labs/misc-addons pull request #525
Opened 2018-01-16 09:04 UTC by iledarn

2018-01-16 23:56 UTC, yelizariev commented on ir_attachment_url/controllers/main.py
> +    @http.route('/mail/<string:res_model>/<int:res_id>/avatar/<int:partner_id>', type='http', auth='public')
Use empty decorator if you don't change anything there, i.e.

``@http.route()``

2018-01-16 23:56 UTC, yelizariev commented on ir_attachment_url/controllers/main.py
> +            response = super(MailControllerExtended, self).avatar(res_model, res_id, partner_id)
It's probably better to don't call super to repeat access checking and so on

2018-01-17 05:50 UTC, iledarn commented on ir_attachment_url/controllers/main.py
> +            response = super(MailControllerExtended, self).avatar(res_model, res_id, partner_id)
I don't think that not using the super is better than repeat some code

2018-01-17 05:55 UTC, iledarn commented on ir_attachment_url/controllers/main.py
> +            response = super(MailControllerExtended, self).avatar(res_model, res_id, partner_id)
The other way may be to take the super `response` and check if response.status == '301' and then try to decode again response.data - to get the url

2018-01-17 06:12 UTC, iledarn commented on ir_attachment_url/controllers/main.py
> +            response = super(MailControllerExtended, self).avatar(res_model, res_id, partner_id)
The other way is failed on encoding decoded url

>>> import base64
>>> url = 'https://www.it-projects.info'
>>> urldecoded = base64.b64decode(url)
>>> urldecoded
'\x86\xdbi\xb3\xff\xf0\xc3\x08\xad\xa6\xba#y\xcbl\x8aw\xe8'
>>> urlafter = base64.b64encode(urldecoded)
>>> urlafter
'https//wwwitprojectsinfo'

2018-01-23 10:54 UTC, ilmir-k commented
@iledarn need to change module version

2018-01-23 11:23 UTC, yelizariev requested changes

2018-01-23 11:23 UTC, yelizariev commented on ir_attachment_url/__init__.py
> +    from . import controllers
Add comment Why

2018-01-23 11:49 UTC, merged