[10.0][PORT] porting project_timelog from 9.0 to 10.0
itpp-labs/misc-addons pull request #559
Opened 2018-02-27 08:04 UTC by GabbasovDinar

2018-04-03 08:16 UTC, Railia requested changes
@GabbasovDinar When I start project_timelog_tour then it is failed on 'Click the button of edit' step

2018-04-03 09:26 UTC, GabbasovDinar commented
@Railia tests don't work. I created the issue https://github.com/it-projects-llc/misc-addons/issues/531

2018-06-19 07:53 UTC, yelizariev commented
```
2018-06-18 15:09:18,488 2376 WARNING 17633-559-519928-base odoo.fields: Field project.task.datetime_stopline: parameter 'select' is no longer supported; use 'index' instead.
2018-06-18 15:09:18,677 2376 INFO 17633-559-519928-base odoo.modules.registry: module project_timelog: creating or updating database tables
2018-06-18 15:09:19,450 2376 INFO 17633-559-519928-base odoo.addons.auth_crypt.models.res_users: Hashing passwords, may be slow for databases with many users...
2018-06-18 15:09:19,825 2376 INFO 17633-559-519928-base odoo.models: Storing computed values of project.timelog fields corrected_duration, duration, project_name, task_name, work_name
2018-06-18 15:09:19,929 2376 INFO 17633-559-519928-base odoo.modules.loading: loading project_timelog/security/ir.model.access.csv
2018-06-18 15:09:20,120 2376 INFO 17633-559-519928-base odoo.modules.loading: loading project_timelog/views/project_timelog_views.xml
2018-06-18 15:09:21,128 2376 INFO 17633-559-519928-base odoo.modules.loading: loading project_timelog/views/res_config_view.xml
2018-06-18 15:09:21,227 2376 WARNING 17633-559-519928-base odoo.addons.base.ir.ir_model: Creating the ir.model.data menu_timelog_config in module base_setup instead of project_timelog.
2018-06-18 15:09:21,235 2376 INFO 17633-559-519928-base odoo.modules.loading: loading project_timelog/views/project_timelog_templates.xml
```

2018-06-19 08:18 UTC, GabbasovDinar commented
@yelizariev DONE

2018-06-19 09:02 UTC, yelizariev requested changes

2018-06-19 09:02 UTC, yelizariev commented on project_timelog/static/description/index.html
> +        <li><a href="mailto:it@it-projects.info">it@it-projects.info <i class="fa fa-envelope-o"></i></a></li>
revert back to ``apps@``

2018-06-19 10:48 UTC, GabbasovDinar commented
@yelizariev DONE

2018-07-11 10:45 UTC, Railia approved these changes

2018-10-16 12:12 UTC, Ramil-Mukhametzyanov requested changes
The subtask counter stops and the warning signal is played twice. The first is at the unpredictable time (the color does not change), and  the second is when the subtask counter reaches the subtask completion time from the project_timelog setting.

Browser console error when subtask counter reaches completion time:
Uncaught (in promise) DOMException: The play() request was interrupted by a new load request. https://goo.gl/LdLk22

Testing parameters:
Set warning time: 00:01
Set completion time: 00:05
On runbot with updated and explicit modules.

2018-11-21 12:05 UTC, Ramil-Mukhametzyanov approved these changes
It works fine on fast processors with high speed internet connections.

2019-07-02 14:16 UTC, KolushovAlexandr commented
superseded by https://github.com/it-projects-llc/misc-addons/pull/772

2019-07-02 14:16 UTC, closed without merging