[FIX] Save button on POS creating/editing
itpp-labs/misc-addons pull request #564
Opened 2018-03-16 12:54 UTC by KolushovAlexandr

2018-03-16 14:50 UTC, Railia approved these changes

2018-03-16 14:59 UTC, yelizariev requested changes

2018-03-16 14:59 UTC, yelizariev commented on web_debranding/doc/changelog.rst
> +- FIX: Save button on POS creating/editing
It’s not clear what was wrong with save button

2018-03-17 01:34 UTC, yelizariev approved these changes

2018-03-19 08:29 UTC, ilmir-k commented
@yelizariev I think it can be merged

2018-03-20 11:27 UTC, merged

2018-03-21 14:12 UTC, zankia commented
Hello,
The [FIX] commit only changes the changelog file. Isn't something missing ?