10.0 ir attachment s3 non superusers dont get credentials
itpp-labs/misc-addons pull request #599
Opened 2018-05-29 13:17 UTC by iledarn

2018-05-29 13:31 UTC, yelizariev submitted a review, later dismissed

2018-05-29 13:31 UTC, yelizariev commented
@iledarn update version and changelog

2018-05-30 19:43 UTC, iledarn commented on ir_attachment_s3/models/ir_attachment.py
> +            s3_records = self.sudo().search([('id', 'in', self.ids)] + condition)
Иван, в этом месте обычный юзер без sudo() не находит собственный id аттачмента (в self.ids его нету), соответственно s3_records пустой получается.
Если sudo() поставить, то все находится. Но: в результирующем s3_records получается поле ``datas`` пустым.

2018-05-30 20:04 UTC, iledarn commented
@yelizariev , done

2018-05-30 21:18 UTC, yelizariev requested changes

2018-05-30 21:18 UTC, yelizariev commented on ir_attachment_s3/doc/changelog.rst
> +- **FIX:** non-supersusers cannot get attachments in s3
*get* or *save*?

2018-05-30 21:18 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +        for attach in self & s3_records:
You add comment that explain why this ``&`` operation

2018-05-30 21:26 UTC, iledarn commented on ir_attachment_s3/doc/changelog.rst
> +- **FIX:** non-supersusers cannot get attachments in s3
get it = save

2018-05-30 21:27 UTC, iledarn commented on ir_attachment_s3/doc/changelog.rst
> +- **FIX:** non-supersusers cannot get attachments in s3
get from S3 = get

2018-05-30 21:29 UTC, yelizariev approved these changes

2018-06-01 09:11 UTC, Railia approved these changes

2018-06-01 09:15 UTC, merged