Update index.rst
itpp-labs/misc-addons pull request #612
Opened 2018-06-19 06:51 UTC by Railia

2018-06-19 07:40 UTC, yelizariev commented on ir_config_parameter_multi_company/doc/index.rst
> +  Note: Make sure that the same value for all companies (leave the default value). Follow the steps:
Why?

2018-06-19 07:42 UTC, yelizariev commented on ir_config_parameter_multi_company/doc/index.rst
> +* Find this value in every Company and delete it. Leave the default value only.
Which value?

2018-06-19 07:43 UTC, yelizariev requested changes
You shall not ask to delete all values. Some parameters brake the database once it completely deleted

2018-06-19 09:12 UTC, yelizariev requested changes

2018-06-19 09:12 UTC, yelizariev commented on ir_config_parameter_multi_company/doc/index.rst
> +* Go to ``Settings >> General Settings >> Technical>> Parameters >> Company Properties``
missed space

2018-06-19 09:12 UTC, yelizariev commented on ir_config_parameter_multi_company/doc/index.rst
> +* Change the value (database expiration, for example) for every company. It must be the same as Default value.
+* Change the value (database expiration, for example) for every company. It must be the same as Default value.

Why? You can keep only default value, no need to update for every company

2018-06-19 09:15 UTC, yelizariev commented
Also, make a separate section for new note. You put it to `` Protected properties``, but the note is not always related to protected properties

2018-06-19 09:55 UTC, yelizariev commented on ir_config_parameter_multi_company/doc/index.rst
> +There are cases when you change companies values (for example Database expiration). And this can lead to errors in the ir_config_parameter_multi_company module operation.
> There are cases when you change companies values (for example Database expiration). And this can lead to errors in the ir_config_parameter_multi_company module operation.

It's fixed and imposible to do anymore. Just make an instuctions how to reset values

2018-06-19 09:55 UTC, yelizariev commented on ir_config_parameter_multi_company/doc/index.rst
> +* Go to `[[ Settings ]] >> General Settings >> Technical>> Parameters >> Company Properties``
missed space again

2018-06-19 09:55 UTC, yelizariev commented on ir_config_parameter_multi_company/doc/index.rst
> +* Find the value (database expiration value, for example) and delete it for every company. Don't delete the default value.
How to find? The menu doesn't show param name

2018-06-19 09:57 UTC, yelizariev requested changes
Don't reference to ``database expiration``. Just make an instruction how set same value for a parameter to all companies

2018-06-27 08:52 UTC, yelizariev requested changes

2018-06-27 08:52 UTC, yelizariev commented on ir_config_parameter_multi_company/doc/index.rst
> +* Go to ``[[ Settings ]] >> General Settings >> Technical>> Parameters >> Company Properties``
missed space again

2018-06-27 08:52 UTC, yelizariev commented on ir_config_parameter_multi_company/doc/index.rst
> +* Click ``[Group By] -> Company``
Does grouping by company really helps?

2018-06-27 08:52 UTC, yelizariev commented on ir_config_parameter_multi_company/doc/index.rst
> +* Find the value form with the value you want to reset and delete the form for every company. Don't delete the default value.
You cannot delete form. Use work *record* instead.

2018-06-29 11:28 UTC, Railia commented on ir_config_parameter_multi_company/doc/index.rst
> +* Click ``[Group By] -> Company``
It helps find unneeded value in every Company

2018-06-29 11:35 UTC, Railia commented on ir_config_parameter_multi_company/doc/index.rst
> +* Find the value form with the value you want to reset and delete the form for every company. Don't delete the default value.
I did this. What do you mean by the word "record"?

2018-06-29 12:00 UTC, yelizariev commented on ir_config_parameter_multi_company/doc/index.rst
> +* Find the value form with the value you want to reset and delete the form for every company. Don't delete the default value.
Запись

2018-06-29 12:05 UTC, yelizariev commented on ir_config_parameter_multi_company/doc/index.rst
> +* Click ``[Group By] -> Company``
It doesn't help much when you have 100+ records. You shall use search or grouping by Model for example. Or several groupings
![screenshot-343610-10-0-13f02f runbot16 odoo com-2018 06 29-17-03-50](https://user-images.githubusercontent.com/186131/42091326-6cf6aa96-7bbe-11e8-8a17-6bf0b5bd1108.png)

2018-06-29 12:14 UTC, Railia commented on ir_config_parameter_multi_company/doc/index.rst
> +* Click ``[Group By] -> Company``
Ok. I'll delete this sentence.

2018-06-29 12:15 UTC, Railia commented on ir_config_parameter_multi_company/doc/index.rst
> +* Find the value form with the value you want to reset and delete the form for every company. Don't delete the default value.
I was confused by the word "work"

2018-06-30 08:35 UTC, yelizariev commented on ir_config_parameter_multi_company/doc/index.rst
> +* Find the value record with the value you want to reset and delete the record for every company. Don't delete the default value.
How to do it? How to find?

2018-06-30 11:54 UTC, Railia commented on ir_config_parameter_multi_company/doc/index.rst
> +* Find the value record with the value you want to reset and delete the record for every company. Don't delete the default value.
Before I wrote: Group by Company. But you told that this is not right.

2018-06-30 15:53 UTC, yelizariev commented on ir_config_parameter_multi_company/doc/index.rst
> +* Find the value record with the value you want to reset and delete the record for every company. Don't delete the default value.
Yes. Both version are not clear

2018-07-04 02:22 UTC, merged