:ambulance: fixed developer mode availability for not admins via drop…
itpp-labs/misc-addons pull request #630
Opened 2018-07-11 13:41 UTC by KolushovAlexandr

…down menu

2018-07-12 11:46 UTC, yelizariev requested changes

2018-07-12 11:46 UTC, yelizariev commented on web_debranding/models/res_users.py
> +        return self._is_admin()
:+1:

2018-07-12 11:46 UTC, yelizariev commented on web_debranding/static/src/js/user_menu.js
> +            this._rpc({
You must call it only after ``result.then(...)``

2018-07-12 11:49 UTC, yelizariev requested changes
Add unit tests

2018-07-13 07:10 UTC, yelizariev requested changes

2018-07-13 07:10 UTC, yelizariev commented on web_debranding/tests/test_developer_mode_icon.py
> +    def test_02_remove_add_to_cart(self):
cart?

2018-07-16 13:47 UTC, yelizariev requested changes

2018-07-16 13:47 UTC, yelizariev commented on web_debranding/tests/test_developer_mode_menu_elements.py
> +                            console.log('ok');
You must check that the page is load and checking for some elements makes sense

2018-07-16 13:47 UTC, yelizariev commented on web_debranding/tests/test_developer_mode_menu_elements.py
> +                            console.log('error', 'Developer mode menu elements are not displayed for admin');
No need to wait 30*interval  ms each time. You only need to wait when page is loaded and then check condition once

2018-07-17 05:15 UTC, yelizariev requested changes
Use setInterval and check that page is loaded (e.g. top menu is presented)

2018-07-17 05:15 UTC, yelizariev commented on web_debranding/tests/test_developer_mode_menu_elements.py
> +                    $(document).ready( function() {
`` $(document).ready`` may not be enough if targe html rendered via js and not on server side

2018-07-17 05:15 UTC, yelizariev commented on web_debranding/tests/test_developer_mode_menu_elements.py
> +                        }, 3000);
It's not stable solution

2018-07-17 09:51 UTC, yelizariev requested changes
Tests looks fine

2018-07-17 09:51 UTC, yelizariev commented on web_debranding/static/src/js/user_menu.js
> +            return result;
I am not sure how it works, it ``.then`` returns new object and doesn't modify ``result``. If so, you return wrong object

2018-07-17 09:52 UTC, yelizariev requested changes

2018-07-17 09:52 UTC, yelizariev commented on web_debranding/tests/__init__.py
> +# License LGPL - 3.0 or later(https: // www.gnu.org / licenses / lgpl.html).
Why so strange link?

2018-07-17 10:57 UTC, yelizariev requested changes

2018-07-17 10:57 UTC, yelizariev commented on web_debranding/__init__.py
> +# License LGPL - 3.0 or later(https: // www.gnu.org / licenses / lgpl.html).
Fix licenses

2018-07-17 10:57 UTC, yelizariev commented on web_debranding/models/__init__.py
> +# License LGPL - 3.0 or later(https: // www.gnu.org / licenses / lgpl.html).
Fix licenses

2018-07-17 10:57 UTC, yelizariev commented on web_debranding/models/__init__.py
> +# License LGPL - 3.0 or later(https: // www.gnu.org / licenses / lgpl.html).
Fix other spaces too. Compare your comment with 

    # License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).

2018-07-17 11:46 UTC, yelizariev approved these changes

2018-08-07 11:22 UTC, ilmir-k approved these changes

2018-08-09 15:21 UTC, merged