:arrow_up::one::two: web_debranding
itpp-labs/misc-addons pull request #633
Opened 2018-07-23 09:57 UTC by RafiZz

2018-07-24 04:54 UTC, yelizariev requested changes

2018-07-24 04:54 UTC, yelizariev commented on web_debranding/README.rst
> +    This provides a big part of debranding. You can find examples at menu ``[[ Invoicing ]] >> Dashboard >> Reconcile 5 items >> 'Automatic reconcilation' button title on hover``
Try to find example, that doesn't require to install extra modules

2018-07-24 04:54 UTC, yelizariev commented on web_debranding/__manifest__.py
> -        'access_apps',
Why do you remove access_apps? If it's temporarily, you must comment it out instead

2018-07-24 04:54 UTC, yelizariev commented on web_debranding/models/ir_translation.py
> +        super(IrTranslation, self).clear_caches()
It's not obvious why you call it via ``super``. Add a code comment  about it

2018-07-24 13:10 UTC, RafiZz commented on web_debranding/__manifest__.py
> -        'access_apps',
I deleted access_app because the access_settings_menu's dependencies contain access_apps.

2018-07-25 08:24 UTC, ufaks commented on web_debranding/README.rst
> +    This provides a big part of debranding. You can find examples at menu ``[[ Invoicing ]] >> Dashboard >> Reconcile 5 items >> 'Automatic reconcilation' button title on hover``
All examples in depended modules are replaced/hided via other ways in this module

2018-07-27 18:09 UTC, yelizariev commented on web_debranding/__manifest__.py
> -        'access_apps',
ok

2018-07-27 18:10 UTC, yelizariev commented on web_debranding/README.rst
> +    This provides a big part of debranding. You can find examples at menu ``[[ Invoicing ]] >> Dashboard >> Reconcile 5 items >> 'Automatic reconcilation' button title on hover``
What do you mean&

2018-07-27 18:31 UTC, yelizariev commented on web_debranding/README.rst
> +    This provides a big part of debranding. You can find examples at menu ``[[ Invoicing ]] >> Dashboard >> Reconcile 5 items >> 'Automatic reconcilation' button title on hover``
ok

2018-07-27 18:33 UTC, yelizariev commented on web_debranding/models/ir_translation.py
> +        super(IrTranslation, self).clear_caches()
Why it's super and not just ``self.clear_caches()``?

2018-08-03 07:49 UTC, yelizariev commented on web_debranding/models/ir_translation.py
> +    def super_clear_caches(self):
word ``super`` in method name doesn't seem to be relevant

2018-08-03 07:49 UTC, yelizariev commented on web_debranding/models/ir_translation.py
> +        we wrapped it in the api.model decorator
You  need to correct your statement, because It could an ``api.multi`` too

https://github.com/OCA/website/blob/11.0/website_multi_theme/data/themes_default.xml#L17-L20
https://github.com/OCA/website/blob/11.0/website_multi_theme/wizards/website_config_settings.py#L16-L22

2018-08-03 07:49 UTC, yelizariev commented on web_debranding/security/web_debranding_security.xml
> + </odoo>
Maybe just remove the file :wink:

2018-08-03 08:40 UTC, yelizariev commented on web_debranding/models/ir_translation.py
> +        we wrapped it in the api.model decorator
Actually, it's ok

2018-08-06 12:41 UTC, ufaks approved these changes

2018-08-06 12:50 UTC, yelizariev approved these changes
:+1:

2018-08-06 12:52 UTC, merged