:rainbow: details_model_record field refactor
itpp-labs/misc-addons pull request #634
Opened 2018-07-27 09:29 UTC by KolushovAlexandr

2018-08-08 16:11 UTC, ilmir-k approved these changes

2018-08-08 16:21 UTC, ilmir-k commented
@KolushovAlexandr change the version please

2018-08-09 10:09 UTC, yelizariev requested changes

2018-08-09 10:09 UTC, yelizariev commented on base_details/models/base_details.py
> +    details_model_record = fields.Reference(selection="_compute_details_model_record", string='Record')
Don't use ``_compute`` prefix for selection

2018-08-09 10:09 UTC, yelizariev commented on base_details/models/base_details.py
> +    @api.onchange('details_model_exists', 'details_model_record')
Why it's ``onchange`` and not ``api.depends``?

2018-08-09 12:12 UTC, KolushovAlexandr commented on base_details/models/base_details.py
> +    @api.onchange('details_model_exists', 'details_model_record')
@yelizariev Because it should be updated right on the form

2018-08-09 14:08 UTC, yelizariev approved these changes

2018-08-09 14:10 UTC, merged