:arrow_up::one::two: ir_attachment_url
itpp-labs/misc-addons pull request #674
Opened 2018-10-31 10:05 UTC by RafiZz

2018-10-31 10:08 UTC, RafiZz commented on ir_attachment_url/models/ir_http.py
> +                                             related_id=related_id):
This code from odoo.

2018-11-05 13:13 UTC, yelizariev requested changes
Don't change version. We don't do it for migration updates. We update only prefix (11.0 to 12.0)

2018-11-05 13:13 UTC, yelizariev commented on ir_attachment_url/doc/changelog.rst
> +- **Fix** The `binary_content` method is aligned with the original method for easier identification of changes.
No need to add migration updates to changelog. You can make those notes in commit message, but not here

2018-11-05 13:13 UTC, yelizariev commented on ir_attachment_url/models/ir_http.py
> +                                             related_id=related_id):
It's better to fix it to avoid this warnings each time

2018-11-05 13:14 UTC, yelizariev commented on ir_attachment_url/models/ir_http.py
> +                                             related_id=related_id):
It's better to fix it to avoid this warnings each time

2018-11-06 07:20 UTC, RafiZz commented on ir_attachment_url/models/ir_http.py
> +                                             related_id=related_id):
Done.

2018-11-06 07:20 UTC, RafiZz commented on ir_attachment_url/doc/changelog.rst
> +- **Fix** The `binary_content` method is aligned with the original method for easier identification of changes.
Done.

2018-11-13 12:45 UTC, yelizariev requested changes

2018-11-13 12:45 UTC, yelizariev commented on ir_attachment_url/models/image.py
> +def updated_image_resize_images(vals, big_name='image', medium_name='image_medium', small_name='image_small', sizes=None):
I cannot find ``updated_image_resize_images`` in odoo source. Do we need this method here?

2018-11-13 12:54 UTC, yelizariev commented
@RafiZz also fix lint:

ir_attachment_url/models/ir_http.py:86:25: F841 local variable 'last_update' is assigned to but never used

2018-11-13 14:19 UTC, RafiZz commented on ir_attachment_url/models/image.py
> +def updated_image_resize_images(vals, big_name='image', medium_name='image_medium', small_name='image_small', sizes=None):
"updated_" is a prefix in order to show that it is changed. The original function is called "image_resize_images". I made the code so that it looked like other code in the same file.

2018-11-14 13:43 UTC, yelizariev requested changes

2018-11-14 13:43 UTC, yelizariev commented on ir_attachment_url/models/ir_http.py
> +                        del last_update
:-1:

2018-11-28 13:19 UTC, yelizariev approved these changes

2018-11-29 09:10 UTC, Ramil-Mukhametzyanov commented on ir_attachment_url/__manifest__.py
> +    "version": "12.0.1.1.6",
The version number should be changed to 12.0.1.1.7

2018-12-06 06:02 UTC, Ramil-Mukhametzyanov approved these changes

2018-12-06 10:39 UTC, merged