10.0-ir_attachment_url-image_resize_fix
itpp-labs/misc-addons pull request #681
Opened 2018-11-14 09:49 UTC by RafiZz

When the "image_resize_image" function was called, they received the error "binascii.Error: decoding with base64 codec failed (Error: Incorrect padding)", since the value of the binary field is the URL, not the base_64 string.

2018-11-14 11:47 UTC, yelizariev requested changes

2018-11-14 11:47 UTC, yelizariev commented on ir_attachment_url/doc/changelog.rst
> +`1.1.6`
No update in manifest file

2018-11-14 11:47 UTC, yelizariev commented on ir_attachment_url/models/ir_http.py
> +                        del last_update
:-1: You shall not assign variable instead

2018-11-14 11:58 UTC, RafiZz commented on ir_attachment_url/doc/changelog.rst
> +`1.1.6`
Do I need to move the message line to 1.1.5 or delete it completely?

2018-11-14 12:30 UTC, RafiZz commented on ir_attachment_url/doc/changelog.rst
> +`1.1.6`
Done.

2018-11-14 12:30 UTC, RafiZz commented on ir_attachment_url/models/ir_http.py
> +                        del last_update
Done.

2018-11-15 13:00 UTC, yelizariev commented
Still 

ir_attachment_url/models/ir_http.py:84:13: F841 local variable 'last_update' is assigned to but never used

2018-11-21 06:57 UTC, merged