11.0 bc375d9170a5576eee8e81d10c2ed980c3541b13
itpp-labs/misc-addons pull request #686
Opened 2018-11-21 08:38 UTC by Rusllan

2018-11-23 13:49 UTC, yelizariev approved these changes

2018-11-23 13:49 UTC, yelizariev commented on ir_attachment_s3/doc/changelog.rst
> +- **Improvement:** Save resized image to s3 instead of passing original (big) image
New update to test

2018-11-23 13:49 UTC, yelizariev commented on ir_attachment_url/doc/changelog.rst
> +- **Fix:** Product Variant were downloaded on server instead of passing url
New update to test

2018-12-04 11:22 UTC, Ramil-Mukhametzyanov requested changes
1. Open Website>Configuration>Settings
2. Set Product Catalog>Attributes and Variants
3. Go to Catalog>Product Variants
4. Choose and click edit a product.
5. Change the product image using a link 
Result:
binascii.Error: decoding with 'base64' codec failed (Error: Incorrect padding)

2018-12-05 14:06 UTC, Ramil-Mukhametzyanov approved these changes

2018-12-05 15:47 UTC, merged