:ambulance: web_website fixes after odoo update
itpp-labs/misc-addons pull request #693
Opened 2018-12-03 13:44 UTC by KolushovAlexandr

2018-12-07 11:28 UTC, yelizariev requested changes

2018-12-07 11:28 UTC, yelizariev commented on web_website/models/ir_property.py
> +        # We override the super method to make it website dependent
Mark code that is new and\or make overview of difference with origin

2018-12-07 11:28 UTC, yelizariev commented on web_website/tests/test_website_dependent.py
> +        # wdb.set_trace()
:-1:

2018-12-07 11:58 UTC, yelizariev requested changes

2018-12-07 11:58 UTC, yelizariev commented on web_website/models/ir_property.py
> +                    result[id] = default_value
It's hard to read. Use variabls, e.g.

website_id  = result[3]

2018-12-07 14:30 UTC, yelizariev commented on web_website/models/ir_property.py
> +            # retrieve values: p.res_id is formatted as "<rec._name>,<rec.id>"
fix comment

2018-12-07 14:31 UTC, yelizariev commented on web_website/models/ir_property.py
> +                      or self.env['res.company']._company_default_get(model, field_id).id)
no need for parenthesises

2018-12-07 14:34 UTC, yelizariev commented on web_website/models/ir_property.py
> +        default_value = result.pop(None, None)
```suggestion
        # Take value for None key, i.e. 
        # {{None: (None, val0, company_id0, website_id0), ...}, res_id1: (res_id1, val1, company_id1, website_id1), ...}
        default_value = result.pop(None, None)
```

2018-12-10 09:46 UTC, KolushovAlexandr commented
11v branch should be updated at first

2018-12-10 09:46 UTC, closed without merging