10.0 fix ir attachment url getting mimetype
itpp-labs/misc-addons pull request #699
Opened 2018-12-11 13:51 UTC by RafiZz

2018-12-11 14:23 UTC, yelizariev requested changes
Also, add updating version and add changelog into the first commit

2018-12-11 14:23 UTC, yelizariev commented on ir_attachment_url/models/binary_fields.py
> +# Copyright 2018 Rafis Bikbov <https://www.it-projects.info/team/RafiZz>
Add the rest developers, please

2018-12-12 08:12 UTC, RafiZz commented on ir_attachment_url/models/binary_fields.py
> +# Copyright 2018 Rafis Bikbov <https://www.it-projects.info/team/RafiZz>
Done.

2018-12-12 10:37 UTC, yelizariev commented on ir_attachment_url/doc/changelog.rst
> +- **Fix**  When a link to a picture that does not have an extension is written in a binary field, its mimetype is not determined, which leads to an "binascii.Error: decoding with base64 codec failed
:+1:

2018-12-12 10:44 UTC, yelizariev requested changes

2018-12-12 10:44 UTC, yelizariev commented on ir_attachment_url/models/binary_fields.py
> +                    index_content = mimetype.split('/')[0]
:-1:

2018-12-13 16:06 UTC, RafiZz commented on ir_attachment_url/models/binary_fields.py
> +                    index_content = mimetype.split('/')[0]
Now it is better?

2018-12-14 06:39 UTC, yelizariev requested changes

2018-12-14 06:39 UTC, yelizariev commented on ir_attachment_url/models/binary_fields.py
> +                    mimetype, content = get_mimetype_by_url(value)
The method is called "get mimetype", but it also returns content

2018-12-14 10:04 UTC, RafiZz commented on ir_attachment_url/models/binary_fields.py
> +                    mimetype, content = get_mimetype_by_url(value)
Renamed.

2018-12-18 13:07 UTC, yelizariev approved these changes

2018-12-18 13:07 UTC, merged