[10.0][IMP] ir_attachment modules
itpp-labs/misc-addons pull request #714
Opened 2018-12-29 11:26 UTC by RafiZz

2018-12-29 13:29 UTC, yelizariev requested changes

2018-12-29 13:29 UTC, yelizariev commented on ir_attachment_s3/doc/index.rst
> +  * ``S3_BUCKET``: it is ``s3.bucket`` parameter
add extra empty line

![image](https://user-images.githubusercontent.com/186131/50538816-a3590c00-0b97-11e9-8379-47ab0f7f5872.png)

2018-12-29 13:29 UTC, yelizariev commented on ir_attachment_s3/doc/index.rst
> +  NOTE: if you simultaneously set parameters both in the Environment variables and in the Odoo System parameters, then the Odoo System parameters have the highest priority.
:+1:

2018-12-29 13:30 UTC, yelizariev commented
There is no :fix: emoji :cry:

2018-12-29 13:30 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> -                _logger.info('parameter {} has been created from env {}'.format(param_name, os_var_name))
Update changelog for this

2019-01-09 10:23 UTC, RafiZz commented on ir_attachment_s3/doc/index.rst
> +  * ``S3_BUCKET``: it is ``s3.bucket`` parameter
Done.

2019-01-09 10:23 UTC, RafiZz commented on ir_attachment_s3/models/ir_attachment.py
> -                _logger.info('parameter {} has been created from env {}'.format(param_name, os_var_name))
Done.

2019-01-11 10:05 UTC, yelizariev approved these changes
Code is fine

2019-01-11 10:07 UTC, yelizariev commented
Tests are not passed

2019-03-13 16:37 UTC, yelizariev commented
When it's ready you have to cleanup commits and use release tags only

2019-03-13 16:40 UTC, yelizariev requested changes

2019-03-13 16:40 UTC, yelizariev commented on .travis.yml
> +  - secure: "IFd+iJjl2lUql3Bc7MVWk+0J5wz977v6KYXolh6APbiDoBJ5MNtr8leDe1thf3LjKM590Hq1/Q05COaJVYxo/6+GZh90un/8MGTuQ/nOAbyozhHWPj5MHeOkDWowlJxlNRqNXttpT9EuhJpRJbC9uXUXeFnf1EYAluyB+V3M4SX94kgGEVp71kp7E2
Note, that travis  uses it only in published branches, not in PR. 
Also, add a comment which those variables are about (S3 credentials?)

2019-03-18 09:43 UTC, RafiZz commented on .travis.yml
> +  - secure: "IFd+iJjl2lUql3Bc7MVWk+0J5wz977v6KYXolh6APbiDoBJ5MNtr8leDe1thf3LjKM590Hq1/Q05COaJVYxo/6+GZh90un/8MGTuQ/nOAbyozhHWPj5MHeOkDWowlJxlNRqNXttpT9EuhJpRJbC9uXUXeFnf1EYAluyB+V3M4SX94kgGEVp71kp7E2
Done.

2019-03-21 21:05 UTC, yelizariev requested changes
Looks very professional, but one commit has wrong tag. Replace :fire:  to :shield:

2019-03-21 21:07 UTC, yelizariev commented
@Ramil-Mukhametzyanov or @ilmir-k  (decide yourself who will check it)
updates affect products: at backend (variant and template) at ecommerce (/shop, product pages) -- everywhere it must be url to s3 file with proper size. It cannot be base64 data (check it via network or via "Open image in new tab")

2019-04-18 12:48 UTC, Ramil-Mukhametzyanov requested changes
There is no any record about ir_attachment_url changes in changelog and version is not changed.

2019-07-05 13:27 UTC, KolushovAlexandr commented
superseded by https://github.com/it-projects-llc/misc-addons/pull/775

2019-07-05 13:27 UTC, closed without merging