:arrow_up::one::one:Autostaging_project_task *Port*
itpp-labs/misc-addons pull request #722
Opened 2019-01-23 13:32 UTC by Ommo73

2019-02-04 09:24 UTC, yelizariev requested changes

2019-02-04 09:24 UTC, yelizariev commented on autostaging_project_task/models.py
> +    autostaging_next_stage_related = fields.Many2one('project.task.type', string='Autostaging next stage', related='stage_id.autostaging_next_stage')
Why it's renamed?

2019-02-04 09:24 UTC, yelizariev commented on autostaging_base/README.rst
> +The tasks which are not modified within the idle timeout automatically moved to the next stage (may be used with project.task or crm.lead)
It can be used with any model

2019-02-04 09:24 UTC, yelizariev commented on autostaging_base/__manifest__.py
> +    "summary": """Change stages of tasks automatically after a specified time""",
Tasks?

2019-02-11 11:38 UTC, Ommo73 commented on autostaging_project_task/models.py
> +    autostaging_next_stage_related = fields.Many2one('project.task.type', string='Autostaging next stage', related='stage_id.autostaging_next_stage')
Because the method "_get_model_list" in "autostaging.card" should select only the model "project.task" as it was in previous versions of the module. After the last changes in the module names, the models "project.task" and "project.task.type" had the same field "autostaging_next_stage". This caused an error and the module did not work as before.

2019-02-11 13:26 UTC, closed without merging