11.0 autostaging base porting 2
itpp-labs/misc-addons pull request #724
Opened 2019-01-25 12:08 UTC by Ommo73

2019-01-25 12:59 UTC, yelizariev requested changes

2019-01-25 12:59 UTC, yelizariev commented on autostaging_base/models.py
> +        print('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')
:-1:

2019-01-25 12:59 UTC, yelizariev commented on autostaging_project_task/views.xml
> +            <field name="model_id" ref="model_project_task_type"/>
<field name="model_id" ref="project.model_project_task_type"/>

?

2019-01-30 13:00 UTC, KolushovAlexandr requested changes
1 Update Docs 
2 Rebase commits

2019-01-30 13:00 UTC, KolushovAlexandr commented on autostaging_base/models.py
> +
keep the history clean

2019-01-30 13:00 UTC, KolushovAlexandr commented on autostaging_base/models.py
> +            self.write_date,  DEFAULT_SERVER_DATETIME_FORMAT) + delta).strftime(DEFAULT_SERVER_DATETIME_FORMAT)
keep the history clean

2019-01-31 14:41 UTC, KolushovAlexandr requested changes
All remarks are related to document design. Update commits in order to have by only one porting commit for each module

2019-01-31 14:41 UTC, KolushovAlexandr commented on autostaging_base/__manifest__.py
> +# Copyright 2018 Ildar Nasyrov <https://it-projects.info/>
Wrong, https://github.com/it-projects-llc/misc-addons/commits/12.0/autostaging_base
# Copyright 2015-2017 Ildar Nasyrov <https://it-projects.info/>

add into all required files (*.py, *.xml, *.js) contributors and licenses and don't forget to add in there your name too

2019-01-31 14:41 UTC, KolushovAlexandr commented on autostaging_base/README.rst
> +=================
Here and on the one above should be on more '=' after the name ends, look how in the template https://odoo-development.readthedocs.io/en/latest/dev/docs/README.rst.html

2019-01-31 14:41 UTC, KolushovAlexandr commented on autostaging_base/__manifest__.py
> +    "version": "11.0.1.0.1",
No need to change version when porting keep 11.0.1.0.0

2019-01-31 14:41 UTC, KolushovAlexandr commented on autostaging_base/doc/changelog.rst
> +`1.0.1`
No need to change version when porting keep 11.0.1.0.0

2019-01-31 14:41 UTC, KolushovAlexandr commented on autostaging_base/doc/index.rst
> +================
One more '=' sign before the name and after

2019-01-31 14:41 UTC, KolushovAlexandr commented on autostaging_base/doc/index.rst
> +=============
May be removed

2019-01-31 14:41 UTC, KolushovAlexandr commented on autostaging_base/doc/index.rst
> +=====
This paragraph is related to autostaging_project_task not to this module

2019-01-31 14:41 UTC, KolushovAlexandr commented on autostaging_project_task/README.rst
> +=========================
one more '=' is needed

2019-01-31 14:41 UTC, KolushovAlexandr commented on autostaging_project_task/__manifest__.py
> +# Copyright 2018 Ildar Nasyrov <https://it-projects.info/>
Update copyrights in all required files

2019-01-31 14:41 UTC, KolushovAlexandr commented on autostaging_project_task/doc/index.rst
> +Autostaging project task
Whitespace at the line start is missed

2019-02-01 12:35 UTC, closed without merging