:zap: autocheckout feature
itpp-labs/misc-addons pull request #728
Opened 2019-02-08 14:09 UTC by KolushovAlexandr

2019-03-12 07:41 UTC, Ramil-Mukhametzyanov commented on base_attendance/static/src/js/kiosk_confirm.js
> +        }, 900);
how this value is computed? why here is this change?

2019-03-12 10:53 UTC, Ramil-Mukhametzyanov commented on base_attendance/static/src/js/kiosk_mode.js
> +                if (unhexed_code.length % 2) {
why is this part necessary?

2019-03-12 11:19 UTC, Ramil-Mukhametzyanov requested changes
1."No partner corresponding to barcode ... " error appears while scanning barcode in Kiosk mode
2. The "HEX type" checkbox should be added. Without a type defined clarily, it is confusing which barcode the module searches. For example, hexadecimal 0x1273 (=4723) and decimal 1273.

2019-03-13 15:44 UTC, KolushovAlexandr commented on base_attendance/static/src/js/kiosk_mode.js
> +                if (unhexed_code.length % 2) {
Some of RFID scanners interpret RFID as HEX instead of DEC, so this part was made for these device types.

2019-03-13 15:44 UTC, KolushovAlexandr commented on base_attendance/static/src/js/kiosk_confirm.js
> +        }, 900);
It's needed for ui tests. Clock updates somehow distract tour manager and it raises an error even when everything's ok.

2019-03-13 15:45 UTC, KolushovAlexandr commented
@Ramil-Mukhametzyanov 
1."No partner corresponding to barcode ... " error appears while scanning barcode in Kiosk mode

It was tested in production everything worked. I need more explanation.

2. The "HEX type" checkbox should be added. Without a type defined clarily, it is confusing which 
barcode the module searches. For example, hexadecimal 0x1273 (=4723) and decimal 1273.

Some devices scan regular barcodes as HEX, so the update related to HEX barcodes searches scanned barcode (it depends on scanning device it might be two types: normal DEC and HEX) then if nothing's found it searches unHEXed barcode. If nothing's found raises an error notification. I can delete it, not sure if it's needed for us. For the festival it was necessary and it worked in both device types for regular and ones that interpret barcodes as HEX.

2019-03-14 07:19 UTC, Ramil-Mukhametzyanov reviewed
Example, more detailed:
Attendant1  - 4723 = 0x1273,
Attendant2  - 1273.
If scanner gives decimal 1273, the module will make record for the Attendant2.
If scanner gives hexadecimal 0x1273, the module will search the string "1273" and again find matching with the Attendant2 first, but not Attendant1.
We have at least 1700 such number that in hex represented by 4 decimal digits and after convertion to DEC have 4 digits.

2019-03-14 07:29 UTC, Ramil-Mukhametzyanov reviewed
ok. We just can write a note on the description, that only one type of the barcode scanner should be used with the module after database is filled with attendances' barcodes.

2019-03-14 15:52 UTC, KolushovAlexandr commented
@Ramil-Mukhametzyanov We discussed it with Ivan. Barcodes for different types of models have to have different prefixes 2-3 numbers, therefore, there should not be such problems. So, anyway, it will be better to make this functionality as optional.

2019-03-15 08:50 UTC, Ramil-Mukhametzyanov approved these changes

2019-03-15 21:33 UTC, yelizariev commented on base_attendance/models/res_attendance.py
> +        max_interval = self.env['base.config.settings'].shift_autocheckout
It's TransientModel. What the hell?

2019-03-15 21:35 UTC, yelizariev commented on web_debranding/security/web_debranding_security.xml
> +<odoo></odoo>
Why don't you just remove it?

2019-03-15 21:40 UTC, KolushovAlexandr commented on web_debranding/security/web_debranding_security.xml
> +<odoo></odoo>
idk for smth it was kept, I continue

2019-03-15 21:57 UTC, yelizariev commented on web_debranding/security/web_debranding_security.xml
> +<odoo></odoo>
It's already removed in other version, if I'm not wrong

2019-03-19 09:02 UTC, Ramil-Mukhametzyanov requested changes
Autocheckout does not work properly.
![partner autocheckout](https://user-images.githubusercontent.com/33877236/54592971-44e15280-4a4f-11e9-93cf-f74ae7a6fe2e.jpg)
Autocheckout = 30

2019-03-25 09:10 UTC, Ramil-Mukhametzyanov approved these changes

2019-03-25 16:17 UTC, yelizariev approved these changes

2019-03-25 16:19 UTC, merged