11.0 autostaging base port
itpp-labs/misc-addons pull request #729
Opened 2019-02-11 13:56 UTC by Ommo73

2019-02-11 22:01 UTC, KolushovAlexandr requested changes

2019-02-11 22:01 UTC, KolushovAlexandr commented on autostaging_base/README.rst
> +Change stages of tasks automatically after a specified time
It is base module it works with different models. Word task is wrong here

2019-02-11 22:01 UTC, KolushovAlexandr commented on autostaging_base/README.rst
> +The tasks which are not modified within the idle timeout automatically moved to the next stage
The same. Change the word task to the word record or smth else

2019-02-11 22:01 UTC, KolushovAlexandr commented on autostaging_project_task/__manifest__.py
> +    "category": "Autostaging",
Wrong category. it should be 'Project'

2019-02-11 22:01 UTC, KolushovAlexandr commented on autostaging_base/__manifest__.py
> +    "category": "Autostaging",
"Hidden"

2019-02-11 22:16 UTC, KolushovAlexandr commented on autostaging_base/__manifest__.py
> +    "category": "Autostaging",
Perhaps im not really sure, better ask Ilmir about it

2019-02-12 03:14 UTC, yelizariev commented on autostaging_base/__manifest__.py
> +    "category": "Autostaging",
It's not strictly specified... Probably the rule is "If it's technical module for more than one module modules, then don't use Hidden"

2019-02-12 03:14 UTC, yelizariev commented on autostaging_project_task/__manifest__.py
> +    "category": "Autostaging",
It would be ok to have new category, but only when we have a set of modules with shared ideas.

2019-02-14 16:11 UTC, KolushovAlexandr approved these changes

2019-02-20 11:42 UTC, Ramil-Mukhametzyanov requested changes
Autostaging moves a task to a stage that is not in the project
Steps to reproduce :
1. Select two projects
* I chose "E-Learning Intergation" and "Research&Development"
2. Create a stage for one of the projects.
* I created a "Learned" stage for the "E-Learning Intergation" project
3. Create a stage for both projects.
* I created a stage "Study"
4. Set the autostaging from the second stage to the first stage
* Enable autostaging for "Study" , the next stage "Learned"
5. Create a tasks in projects in the "Study" stage
* "Research 1" task in the "Research and Development" project
Result: After the autostaging, the task stage will be changed to a stage that does not exist in the project.
* Task "Research 1" in the "Learned" stage
![study](https://user-images.githubusercontent.com/33877236/53089443-6c1b3180-352e-11e9-84e8-831376cc7afc.jpg)
![learned](https://user-images.githubusercontent.com/33877236/53089463-74736c80-352e-11e9-909a-03f2a5de21d1.jpg)

2019-02-21 09:01 UTC, Ramil-Mukhametzyanov requested changes
@Ommo73 
not allow to save changes of autostaging settings if the next stage does not exist in one or more projects of edited stage.

2019-02-26 17:11 UTC, KolushovAlexandr approved these changes

2019-03-01 07:11 UTC, Ramil-Mukhametzyanov approved these changes
We do not have to improve the module in this PR.

2019-03-01 13:42 UTC, yelizariev reviewed
Add yourself to copyright lines and contributors list. Cleanup commits

2019-03-12 16:24 UTC, yelizariev requested changes
Code update in base_attendance is fine

2019-03-12 16:24 UTC, yelizariev commented on base_attendance/doc/changelog.rst
> +- **Fix:** Error related to incorrect attribute name
Too technical. Describe when error happened instead

2019-03-12 16:27 UTC, yelizariev commented
@Ommo73 you don't really need to put work "Port" in commit message as you have commit tags about it. Or at least don't use asterisks 
 :arrow_up::one::one: port autostaging_base
or
 :arrow_up::one::one: autostaging_base

2019-03-12 17:06 UTC, KolushovAlexandr commented on base_attendance/doc/changelog.rst
> +- **Fix:** Error related to incorrect attribute name
Error on error message for incorrect attendance creation

2019-03-20 15:01 UTC, yelizariev requested changes
Clean up commits. It must be just 3 commits



arrow_uponeone autostaging_project_task *Port*

arrow_uponeone autostaging_base *Port*

ambulance incorrect attribute name

2019-03-21 17:23 UTC, yelizariev approved these changes

2019-03-22 12:58 UTC, merged

2019-03-22 19:39 UTC, KolushovAlexandr commented
:heart_eyes: