12.0 autostaging base, autostaging project task porting
itpp-labs/misc-addons pull request #734
Opened 2019-04-01 10:22 UTC by Ommo73

2019-04-03 09:21 UTC, KolushovAlexandr approved these changes

2019-04-03 12:18 UTC, KolushovAlexandr requested changes

2019-04-03 12:18 UTC, KolushovAlexandr commented on autostaging_project_task/__manifest__.py
> +    "price": 30.00,
incorrect price. fix it for the 11v too

2019-04-11 11:18 UTC, Ramil-Mukhametzyanov requested changes
Clicking a task after configuring autostaging cause error.

2019-04-30 13:54 UTC, KolushovAlexandr requested changes
Resolve conflicts

2019-05-08 11:19 UTC, Ramil-Mukhametzyanov approved these changes

2019-05-14 07:54 UTC, KolushovAlexandr approved these changes

2019-05-14 14:07 UTC, yelizariev approved these changes

2019-05-15 06:48 UTC, merged