:arrow_up::one::one: res_partner_skype Port
itpp-labs/misc-addons pull request #736
Opened 2019-04-11 11:53 UTC by Ommo73

2019-04-18 12:47 UTC, KolushovAlexandr requested changes

2019-04-18 12:47 UTC, KolushovAlexandr commented on res_partner_skype/__manifest__.py
> +    "summary": """Send private messages to specified recipients, regardless of who are in followers list.""",
What?

2019-04-18 12:47 UTC, KolushovAlexandr commented on res_partner_skype/static/src/xml/base.xml
> +<t t-name="FieldSkype" t-extend="FieldReference">
Why here is reference field, but in js you extend mail one?

2019-04-30 12:47 UTC, KolushovAlexandr requested changes

2019-04-30 12:47 UTC, KolushovAlexandr commented on res_partner_skype/__manifest__.py
> +    "summary": """Adds skype field to partner form. When you click on skype address, chat window is opened.""",
Adds skype field with a widget which opens skype chat window with the contact account when clicking on it

2019-04-30 12:47 UTC, KolushovAlexandr commented on res_partner_skype/views.xml
> +                        <field name="skype" widget="skype"/>
it seems to be incorrect indent

2019-05-15 11:11 UTC, KolushovAlexandr approved these changes

2019-05-15 14:51 UTC, Ramil-Mukhametzyanov approved these changes

2019-05-16 07:48 UTC, yelizariev requested changes
Looks good :+1:

2019-05-16 07:48 UTC, yelizariev commented on res_partner_skype/README.rst
> +Description: https://www.odoo.com/apps/modules/11.0/res_partner_skype/
That link is already presented below

2019-05-20 09:38 UTC, yelizariev approved these changes

2019-07-05 12:42 UTC, KolushovAlexandr approved these changes

2019-07-05 13:01 UTC, yelizariev approved these changes

2019-07-18 06:31 UTC, em230418 requested changes
Cannot pass tests using odooup.
To reproduce:
```
odooup init test  # Odoo 11, no additional repo
cd test
bash
cd vendor
mkdir Ommo73 && cd Ommo73
git clone git@github.com:Ommo73/misc-addons.git -b 11.0-res_partner_skype_port
exit
make create && make build
docker-compose run dodoo -- init --new-database db --demo -m web,base,res_partner_skype
docker-compose run odoo -d db --test-enable --stop-after-init -i res_partner_skype
```

2019-07-22 07:40 UTC, yelizariev commented
Superseded by #784

2019-07-22 07:40 UTC, closed without merging