12.0 e926e0dc372d2b4f567a0baebe2c0dbe025071b0
itpp-labs/misc-addons pull request #738
Opened 2019-04-12 10:27 UTC by KolushovAlexandr

2019-04-15 12:27 UTC, Ramil-Mukhametzyanov requested changes
broken pincode screen in kiosk mode
![broken pin screen](https://user-images.githubusercontent.com/33877236/56132457-72181680-5fa3-11e9-946f-7524c342b782.jpg)

2019-04-16 10:13 UTC, Ramil-Mukhametzyanov requested changes
Demo user with Partner Attendance Manager access rights cannot enter Kiosk mode.
Error:
Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:
- Administration/Settings

(Document model: ir.config_parameter)

2019-04-16 10:15 UTC, Ramil-Mukhametzyanov requested changes
Very often Odoo session expires.

2019-04-17 09:58 UTC, Ramil-Mukhametzyanov requested changes
The same security issue in base_attendance module: Demo user cannot access Partner Attendances->Configuration

2019-04-17 12:24 UTC, Ramil-Mukhametzyanov commented on project_task_subtask/static/src/css/kanban_styles.css
> +.task_progress {
The task_progress class style is repeated.

2019-04-17 12:24 UTC, Ramil-Mukhametzyanov commented on project_task_subtask/static/src/css/kanban_styles.css
> +.task_progress .task_progress_bar{
Almost all properties of task_progress class style are overridden, except font-size.

2019-04-17 12:51 UTC, Ramil-Mukhametzyanov commented on README.md
> +[![Build Status](https://travis-ci.com/it-projects-llc/misc-addons.svg?branch=10.0)](https://travis-ci.com/it-projects-llc/misc-addons)
Do we need to change the branch here?
misc-addons.svg?branch=12.0

2019-04-18 09:12 UTC, yelizariev commented on README.md
> +[![Build Status](https://travis-ci.com/it-projects-llc/misc-addons.svg?branch=10.0)](https://travis-ci.com/it-projects-llc/misc-addons)
You are right

2019-04-29 12:29 UTC, KolushovAlexandr commented on project_task_subtask/static/src/css/kanban_styles.css
> +.task_progress {
make it a task for 11v

2019-04-30 12:32 UTC, Ramil-Mukhametzyanov approved these changes

2019-04-30 13:23 UTC, yelizariev approved these changes

2019-04-30 13:24 UTC, merged