8.0 project task subtask
itpp-labs/misc-addons pull request #740
Opened 2019-04-22 08:16 UTC by Ommo73

- New: added group "Allow edit others tasks"
- Fix: changed message after status update
- Iprovement: name in the message is not duplicated if reviewer and assigned user are one person

2019-04-30 13:11 UTC, KolushovAlexandr requested changes

2019-04-30 13:11 UTC, KolushovAlexandr commented on project_task_subtask/security/ir.model.access.csv
> +
delete it

2019-04-30 13:11 UTC, KolushovAlexandr commented on project_task_subtask/models/project_task_subtask.py
> +        group_id = self.env['res.groups'].search([('name', '=', 'Allow edit others tasks')])
use `ref` instead of search by name

2019-04-30 13:11 UTC, KolushovAlexandr commented on project_task_subtask/views/project_task_subtask.xml
> +                  <button name="change_state_done" string="Change state to DONE" type="object" icon="gtk-apply" attrs="{'invisible': ['|', ('state', 'in',['done', 'cancelled']), ('hide_button', '=',
keep commit history clean

2019-04-30 13:11 UTC, KolushovAlexandr commented on project_task_subtask/models/project_task_subtask.py
> +                if self.env.user != r.reviewer_id and self.env.user != r.user_id and self.env.user.commercial_partner_id not in r.task_id.message_follower_ids:
i think it should be `partner_id` instead of `commercial_partner_id`

2019-04-30 13:11 UTC, KolushovAlexandr commented on project_task_subtask/models/project_task_subtask.py
>          for r in self:
make a refactor to make the code readable. I mean change r to smth else

2019-04-30 13:11 UTC, KolushovAlexandr commented on project_task_subtask/models/project_task_subtask.py
> +                    raise UserError(_('Only users related to that task can change state.'))
Only users related to that subtask or users with special rights can change state.

2019-05-08 08:47 UTC, KolushovAlexandr requested changes
1 Please squash first two commits and delete there commented code in the security xml file.
2 Also the 3th and the 4thcommits are better to be squashed too because it's the related improvement done in the 4th one
3 correct the changelog after this. It Should contain the line about renamings.

2019-05-08 12:52 UTC, KolushovAlexandr approved these changes

2019-05-15 14:13 UTC, Ramil-Mukhametzyanov requested changes
A task followers can change every To-Do status through Edit button.

2019-05-16 07:15 UTC, Ramil-Mukhametzyanov commented
> can change
even if the user is not in the group "Allow edit others tasks".
The name of the group is confusing. I suppose it should be "Allow editing tasks from other followers"

2019-05-17 13:19 UTC, Ommo73 commented
> A task followers can change every To-Do status through Edit button.

fixed

2019-05-17 15:32 UTC, Ramil-Mukhametzyanov requested changes
A task follower can change each subtask executor using the Edit button.
If he/she is only a reviewer of a subtask, he/she should be able to modify the "Assigned to" field of the subtask (if he/she does not have the permission "Allow edit others tasks")

2019-05-17 15:35 UTC, Ramil-Mukhametzyanov requested changes
A comma is missing between the follower names in the status update message.
![Screenshot_2019-05-17 Tasks - Odoo](https://user-images.githubusercontent.com/33877236/57939117-06e39c00-78e3-11e9-98af-c273bd4432b7.png)

2019-05-20 09:52 UTC, Ramil-Mukhametzyanov approved these changes

2019-05-20 10:21 UTC, merged