:ambulance: print badge error
itpp-labs/misc-addons pull request #742
Opened 2019-04-25 13:25 UTC by KolushovAlexandr

2019-05-14 08:01 UTC, Ramil-Mukhametzyanov requested changes
An empty document is loaded after clicking the Print button.
"The document contains no pages."

2019-07-12 10:59 UTC, Ramil-Mukhametzyanov approved these changes

2019-07-15 06:54 UTC, yelizariev approved these changes
Looks good

2019-07-15 08:51 UTC, ilmir-k approved these changes

2019-07-22 09:33 UTC, em230418 commented
I approve to merge it now

2019-07-22 09:33 UTC, merged