12.0 pad crm port
itpp-labs/misc-addons pull request #747
Opened 2019-05-20 10:26 UTC by Ommo73

2019-05-20 14:05 UTC, Ramil-Mukhametzyanov requested changes

2019-05-20 14:05 UTC, Ramil-Mukhametzyanov commented on pad_crm/__manifest__.py
> +    # "price": 9.00,
Uncomment the price line and change the price to 90 EUR.

2019-05-20 14:18 UTC, KolushovAlexandr commented on pad_crm/__manifest__.py
> +    # "price": 9.00,
use :euro: tag for that

2019-05-21 08:21 UTC, yelizariev approved these changes

2019-05-21 10:18 UTC, Ramil-Mukhametzyanov requested changes

2019-05-21 10:18 UTC, Ramil-Mukhametzyanov commented on pad_crm/README.rst
> +Demo: http://runbot.it-projects.info/demo/addons-dev/12.0
Change the link to http://runbot.it-projects.info/demo/misc-addons/12.0

2019-05-21 11:36 UTC, Ramil-Mukhametzyanov approved these changes

2019-05-21 13:05 UTC, merged