10.0 ir attachment url ecommerce
itpp-labs/misc-addons pull request #775
Opened 2019-07-05 13:22 UTC by KolushovAlexandr

2019-07-11 13:26 UTC, Ramil-Mukhametzyanov approved these changes

2019-07-12 07:25 UTC, yelizariev requested changes

2019-07-12 07:25 UTC, yelizariev commented on .travis.yml
> +  - secure: "SoW2Blve4jUApyF5UfM5NvGQ6ZV4OH6wMUGbcTemx+dMqNZTyTlUDxmVOFgau7M/igcgmmdYcsxmWKR0n40VSaAvtBKSdL7J3Ad7xVBpC1zq6LLrrDmZUL1pCWQUpl1znxcq72H+VmnllgdewU1703cVce2wUWmByGjEEV/VnIqjUfXfzh28ZL4hMr
Delete transfix please. We don't use it anymore

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_s3/controllers/main.py
> +                    attachment = resized_attachment.resized_attachment_id
copy-pasted code (difference in ``field=field`` is not counted). Consider to make a single method instead (event if that method just calls those two methods)

```

        resized_attachment = \
            attachment._get_resized_from_cache(width, height) or \
            attachment._set_resized_to_cache(width, height)
```

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_s3/doc/changelog.rst
> +- **FIX:** The Odoo System parameters saving from the Environment variables removed because then we cannot change parameters through environment variables
This is not the only update
```


        # TODO: if model=="product.product" and field in ('image', 'image_small', 'image_medium')
        # we need to make similar trick, because those fields are computed resizes of image_variant
        # with sizes 64*64, 128*128, 1024*1024
```

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_s3/controllers/main.py
>              attachment = env['ir.http'].find_field_attachment(env, model, field, obj)
I think there is a way to refactor it in way where you can deduplicate this line of code:


`            attachment = env['ir.http']._find_field_attachment(env, model, field, obj.id)
`

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_s3/controllers/main.py
>          # * check that it's image on s3
Please extend this algorithm description according to your updates

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_s3/controllers/main.py
>          # * check that it's image on s3
And probably move it to the method description
```
def content_image(....):
"""* check that ...
* ....
"""
```

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_s3/controllers/main.py
> +                image_variant_attachment = env['ir.http']._find_field_attachment(env, model, 'image_variant', obj.id)
Make some comment what is going on here

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_s3/controllers/main.py
> +        if not (width and height):
In theory, one of the variables could be zero or None. So, you have to use ``if not (width or height)``, if you don't agree you need to fix similar statement above

```
        if not (res.status_code == 301 and (width or height)) and not is_product_product_image:
```

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_url/data/ir_attachment_url_data.xml
> +        'ir_attachment.save_option', 'url'
``ir_attachment_url.storage`` ?

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_s3/doc/changelog.rst
> +- **FIX:** The Odoo System parameters saving from the Environment variables removed because then we cannot change parameters through environment variables
The description says "We removed feature X, because then we cannot use feature X"

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +        return resized_att_id.unlink()
Add a comment why we do it

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +        return resized_ids.unlink() if resized_ids else True
You don't need to check ``resized_ids`` variable

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +                                                 encoding='base64', filetype='PNG')
field ``image`` is also resized. Also, don't copy-paste the code. Use ``for-block`` instead.

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +        }
Do we really need this long-name method?

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_s3/models/res_config.py
> +        selection_add=[('s3', 'Save as a link to the file saved to s3')],
Can the description be shorter?

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_url/models/res_config.py
> +        string='Way to save attachments',
string="Attachment Storage"?

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_s3/tests/test_resized_attachments.py
> +        self.assertEqual(redirected_image_url, product_product_image_attachment.url)
How does it works if you don't have ``image`` case in the inverse method? Fix the tests first.


```


            if attach.res_field == 'image_medium':
                value = tools.image_resize_image(base64_source=attach.datas, size=(128, 128),
                                                 encoding='base64', filetype='PNG')
            elif attach.res_field == 'image_small':
                value = tools.image_resize_image(base64_source=attach.datas, size=(64, 64),
                                                 encoding='base64', filetype='PNG')
```

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_url/controllers/main.py
> +        return res
Why do we change here?

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_url/models/binary_fields.py
> +                    super(Binary, self).write(records, base64source)
Does that mean, that module can be used to save files from url (probably after changing parameter to any other value, say "filestore"). If so, you need to cover this in the docs.
If this code has other purposes too, add a comment here. I guess it pass file content to super in order to handle in s3 module, for example

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_url/models/ir_http.py
> +                mimetype = att.mimetype
Why do we redefine mimetype variable passed to the method? Can original mimetype has not a Non wrong value?

2019-07-12 07:25 UTC, yelizariev commented on ir_attachment_url/models/res_config.py
> +    def set_ir_attachment_save_option(self):
Method is not used?

2019-07-23 05:35 UTC, yelizariev commented
Also, we need an information about caching resized images mechanism in README file @em230418

2019-07-23 05:45 UTC, yelizariev commented
@em230418 another thing to do is refactor ir_attachment_s3, ir_attachment_url module in a way, that we can add other storage support without copy-pasting code. Particularly, the content_image method need to be moved to ir_attachment_url.

Other posible kinds of modules: ir_attachment_ftp, ir_attachment_minio (see #712 )

2019-10-14 11:08 UTC, em230418 commented on ir_attachment_s3/models/ir_attachment.py
> +                'res_field': self.res_field,
Зачем?

2019-10-15 09:20 UTC, closed without merging

2019-10-16 07:40 UTC, em230418 commented on ir_attachment_url/models/binary_fields.py
> +                    super(Binary, self).write(records, base64source)
Если save_option не url - то сохраняет само содежимое файла в базу. Я так понял, именно этот момент надо добавить в документацию?

2019-10-16 09:09 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +                'res_field': self.res_field,
В чем проблема?

2019-10-16 10:43 UTC, em230418 commented on ir_attachment_s3/models/ir_attachment.py
> +                'res_field': self.res_field,
https://github.com/KolushovAlexandr/misc-addons/blob/10.0-ir_attachment_url_ecommerce/ir_attachment_s3/controllers/main.py#L45-L47

Мы на основе вложения, у которого res_field = image_variant, хотим получить или создать вложение c res_field = 'image', 'image_medium' или 'image_small' (переменная field).

Но внезапно этот код решил, что давайка не будем это делать, создадим еще один image_variant (self.res_field), но с размером 'image', 'image_medium' или 'image_small'.

И вот зачем это? Тут даже тесты обламываются, т.к. вот это https://github.com/KolushovAlexandr/misc-addons/blob/10.0-ir_attachment_url_ecommerce/ir_attachment_s3/controllers/main.py#L42 в тестах когда-то вернет кортеж(?) `image_variant_attachment` c ДВУМЯ обьектами, для которого позже вычисление `self.id` выбрасывает исключение.

Да и в целом, коммит на котором это изменение предложено https://github.com/it-projects-llc/misc-addons/pull/775/commits/71c2ab8622158a690664ddf4ff4a384d8a49c4d3, какой-то странный. Потому-что
1. обсуждаемое тут изменение приводит к ошибке
2. без этого можно было обойтись:

```
            if attach.res_field == 'image_medium':
                value = tools.image_resize_image(base64_source=attach.datas, size=(128, 128),
                                                 encoding='base64', filetype='PNG')
            elif attach.res_field == 'image_small':
                value = tools.image_resize_image(base64_source=attach.datas, size=(64, 64),
                                                 encoding='base64', filetype='PNG')
```
Описал тут: https://github.com/it-projects-llc/misc-addons/pull/823#issuecomment-542627312

2019-10-17 10:18 UTC, yelizariev commented on ir_attachment_url/models/binary_fields.py
> +                    super(Binary, self).write(records, base64source)
Если значение не url, то закачивает содержимое ссылки и потом сохраняет это содержимое в базу :thinking: Зачем это нужно? Для s3 вроде не нужно