:arrow_up::one::two:
itpp-labs/misc-addons pull request #801
Opened 2019-08-07 08:55 UTC by fedoranvar

2019-08-14 09:18 UTC, KolushovAlexandr requested changes
Fix travis errors
`Module res_users_signature.models.res_users_signature_models`

2019-08-14 09:18 UTC, KolushovAlexandr commented on res_users_signature/README.rst
> + Signature templates for user email
incorrect indents here and almost everywhere below

2019-08-14 09:18 UTC, KolushovAlexandr commented on res_users_signature/__manifest__.py
>  {
add licenses

2019-08-14 09:18 UTC, KolushovAlexandr commented on res_users_signature/models/res_users_signature_models.py
> +        """ copy-pasted from odoo/addons/base/models/ir_mail_server.py::build_email """
please ensure that it's not outdated

2019-08-14 09:18 UTC, KolushovAlexandr commented on res_users_signature/security/res_users_signature_security.xml
> +    <record id="administrator" model="res.groups">
do not change  indents, just replace **openerp** with **odoo** and that's all

2019-08-14 09:18 UTC, KolushovAlexandr commented on res_users_signature/security/res_users_signature_security.xml
> +    <record id="administrator" model="res.groups">
otherwise, it's  hard to understand did you change smth or not

2019-08-14 09:18 UTC, KolushovAlexandr commented on res_users_signature/views/res_users_signature_views.xml
> +<!--
Why it was left commented? Add a comment with a reason of its necessity or remove it out

2019-08-14 09:18 UTC, KolushovAlexandr commented on res_users_signature_hr/README.rst
> + Signature templates for user email (HR)
Wrong indents. Differs from the template

2019-08-14 10:40 UTC, fedoranvar commented on res_users_signature/models/res_users_signature_models.py
> +        """ copy-pasted from odoo/addons/base/models/ir_mail_server.py::build_email """
checked - not outdated.

Does it need to be stated in code somehow?

2019-08-14 10:42 UTC, KolushovAlexandr commented on res_users_signature/models/res_users_signature_models.py
> +        """ copy-pasted from odoo/addons/base/models/ir_mail_server.py::build_email """
no

2019-08-15 14:52 UTC, KolushovAlexandr requested changes

2019-08-15 14:52 UTC, KolushovAlexandr commented on res_users_signature/__manifest__.py
> +# Copyright 2019 Ivan Yelizariev <https://it-projects.info/team/yelizariev>
some manifests were renamed from __openerp__ files, so the commit history is lost, please check openerp file for the module before 9158b5b4ec5b7700d049b7d83dfdde36f63b7aa7 commit

2019-08-15 14:52 UTC, KolushovAlexandr commented on res_users_signature/doc/index.rst
> +* RESULT: {what user gets, how the modules changes default behaviour}
forgot to update template string

2019-08-15 14:52 UTC, KolushovAlexandr commented on res_users_signature/doc/index.rst
> +Allows create signature templates for users. For example,
the sentence does not suit for the article name

2019-08-15 14:52 UTC, KolushovAlexandr commented on res_users_signature/models/res_users_signature_models.py
> +# Copyright 2019 Ivan Yelizariev <https://it-projects.info/team/yelizariev>
really? look at it
50c8b39bcc482bd80905b861202d8124cba44641

Also, we usually do not relocate files

2019-08-15 14:52 UTC, KolushovAlexandr commented on res_users_signature/models/res_users_signature_models.py
> +# Copyright 2019 Ivan Yelizariev <https://it-projects.info/team/yelizariev>
fix licenses everywhere

2019-08-15 14:52 UTC, KolushovAlexandr commented on res_users_signature/doc/index.rst
> +* Open menu ``[[ {Menu} ]]>> {Submenu} >> {Subsubmenu}``
attributes from template

2019-08-15 14:52 UTC, KolushovAlexandr commented on res_users_signature_hr/views/res_users_signature_hr_views.xml
> +<odoo>
better delete the file at all

2019-08-16 06:58 UTC, fedoranvar commented on res_users_signature/__manifest__.py
> +# Copyright 2019 Ivan Yelizariev <https://it-projects.info/team/yelizariev>
please, explain

2019-08-16 07:00 UTC, fedoranvar commented on res_users_signature/models/res_users_signature_models.py
> +# Copyright 2019 Ivan Yelizariev <https://it-projects.info/team/yelizariev>
i've relocated files because in odoo12 it is a style of placing files

And travis were pointing on this as an error

2019-08-16 07:00 UTC, fedoranvar commented on res_users_signature_hr/views/res_users_signature_hr_views.xml
> +<odoo>
check

2019-08-16 07:00 UTC, fedoranvar commented on res_users_signature/doc/index.rst
> +* Open menu ``[[ {Menu} ]]>> {Submenu} >> {Subsubmenu}``
check

2019-08-19 09:31 UTC, KolushovAlexandr requested changes
Make a note about adding code in ``Code Mode`` or how it is called and proper working code for the example signature

2019-08-20 10:50 UTC, KolushovAlexandr approved these changes
Cool :+1:

2019-08-21 08:02 UTC, Ramil-Mukhametzyanov approved these changes

2019-08-22 08:57 UTC, em230418 requested changes
1. Не обновляются подписи. Когда редактируем пользователя, меняем шаблон подписи (signature template), видим что подпись поменялась. Нажимаем на сохранить, перезагружаем страницу - у пользователя старая подпись.

2. Конструкция if не работает или надо поправить документацию c примером (https://github.com/it-projects-llc/misc-addons/blob/05cad9fcd6040bbb8ae5c74cd32a1b1a31e23805/res_users_signature/doc/index.rst)
![FireShot Capture 16 - test1 - Odoo](https://user-images.githubusercontent.com/52414052/63500335-3b09c280-c4b9-11e9-819b-1aeb9eca68eb.png)

3. Случаем не экранирует тэги? Ожидаю, что тегов видно не будет. Если использовать html-элементы невозможно (т.е. подписи могут быть только plaintext), то поправить документацию (убрать тэги).

4. Допустим поставили двум пользователям один и тот-же signature template. Это admin и demo.
Далее делаем следующее:
Settings -> Users & Companies -> Users -> Marc Demo -> Вкладка Preferences -> Signature template -> Кнопка Update signatures.
Далее выкидывает исключение вот тут:
https://github.com/it-projects-llc/misc-addons/blob/05cad9fcd6040bbb8ae5c74cd32a1b1a31e23805/res_users_signature/models/res_users_signature_models.py#L34

Стек трейс:
```
odoo_1           | Traceback (most recent call last):
odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/models.py", line 4718, in ensure_one
odoo_1           |     _id, = self._ids
odoo_1           | ValueError: too many values to unpack (expected 1)
odoo_1           | 
odoo_1           | During handling of the above exception, another exception occurred:
odoo_1           | 
odoo_1           | Traceback (most recent call last):
odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/http.py", line 661, in _handle_exception
odoo_1           |     return super(JsonRequest, self)._handle_exception(exception)
odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/http.py", line 319, in _handle_exception
odoo_1           |     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/tools/pycompat.py", line 87, in reraise
odoo_1           |     raise value
odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/http.py", line 703, in dispatch
odoo_1           |     result = self._call_function(**self.params)
odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/http.py", line 351, in _call_function
odoo_1           |     return checked_call(self.db, *args, **kwargs)
odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/service/model.py", line 97, in wrapper
odoo_1           |     return f(dbname, *args, **kwargs)
odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/http.py", line 344, in checked_call
odoo_1           |     result = self.endpoint(*a, **kw)
odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/http.py", line 946, in __call__
odoo_1           |     return self.method(*args, **kw)
odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/http.py", line 524, in response_wrap
odoo_1           |     response = f(*args, **kw)
odoo_1           |   File "/opt/odoo/vendor/odoo/cc/addons/web/controllers/main.py", line 966, in call_button
odoo_1           |     action = self._call_kw(model, method, args, {})
odoo_1           |   File "/opt/odoo/vendor/odoo/cc/addons/web/controllers/main.py", line 954, in _call_kw
odoo_1           |     return call_kw(request.env[model], method, args, kwargs)
odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/api.py", line 749, in call_kw
odoo_1           |     return _call_kw_multi(method, model, args, kwargs)
odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/api.py", line 736, in _call_kw_multi
odoo_1           |     result = method(recs, *args, **kwargs)
odoo_1           |   File "/opt/odoo/vendor/it-projects-llc/misc-addons/res_users_signature/models/res_users_signature_models.py", line 89, in action_update_signature
odoo_1           |     r.action_update_signature_one()
odoo_1           |   File "/opt/odoo/vendor/it-projects-llc/misc-addons/res_users_signature/models/res_users_signature_models.py", line 95, in action_update_signature_one
odoo_1           |     self.user_ids.render_signature_id()
odoo_1           |   File "/opt/odoo/vendor/it-projects-llc/misc-addons/res_users_signature/models/res_users_signature_models.py", line 34, in render_signature_id
odoo_1           |     if not self.signature_id:
odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/fields.py", line 979, in __get__
odoo_1           |     record.ensure_one()
odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/models.py", line 4721, in ensure_one
odoo_1           |     raise ValueError("Expected singleton: %s" % self)
odoo_1           | ValueError: Expected singleton: res.users(6, 2)
```

2019-08-22 09:03 UTC, em230418 requested changes
5. Исправить ошибку от тревиса
```
res_users_signature/models/res_users_signature_models.py:39:34: E261 at least two spaces before inline comment
```

2019-08-22 10:12 UTC, fedoranvar commented
> 1. Не обновляются подписи. Когда редактируем пользователя, меняем шаблон подписи (signature template), видим что подпись поменялась. Нажимаем на сохранить, перезагружаем страницу - у пользователя старая подпись.
> 2. Конструкция if не работает или надо поправить документацию c примером (https://github.com/it-projects-llc/misc-addons/blob/05cad9fcd6040bbb8ae5c74cd32a1b1a31e23805/res_users_signature/doc/index.rst)
>    ![FireShot Capture 16 - test1 - Odoo](https://user-images.githubusercontent.com/52414052/63500335-3b09c280-c4b9-11e9-819b-1aeb9eca68eb.png)
> 3. Случаем не экранирует тэги? Ожидаю, что тегов видно не будет. Если использовать html-элементы невозможно (т.е. подписи могут быть только plaintext), то поправить документацию (убрать тэги).
> 4. Допустим поставили двум пользователям один и тот-же signature template. Это admin и demo.
>    Далее делаем следующее:
>    Settings -> Users & Companies -> Users -> Marc Demo -> Вкладка Preferences -> Signature template -> Кнопка Update signatures.
>    Далее выкидывает исключение вот тут:
>    https://github.com/it-projects-llc/misc-addons/blob/05cad9fcd6040bbb8ae5c74cd32a1b1a31e23805/res_users_signature/models/res_users_signature_models.py#L34
> 
> Стек трейс:
> 
> ```
> odoo_1           | Traceback (most recent call last):
> odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/models.py", line 4718, in ensure_one
> odoo_1           |     _id, = self._ids
> odoo_1           | ValueError: too many values to unpack (expected 1)
> odoo_1           | 
> odoo_1           | During handling of the above exception, another exception occurred:
> odoo_1           | 
> odoo_1           | Traceback (most recent call last):
> odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/http.py", line 661, in _handle_exception
> odoo_1           |     return super(JsonRequest, self)._handle_exception(exception)
> odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/http.py", line 319, in _handle_exception
> odoo_1           |     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
> odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/tools/pycompat.py", line 87, in reraise
> odoo_1           |     raise value
> odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/http.py", line 703, in dispatch
> odoo_1           |     result = self._call_function(**self.params)
> odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/http.py", line 351, in _call_function
> odoo_1           |     return checked_call(self.db, *args, **kwargs)
> odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/service/model.py", line 97, in wrapper
> odoo_1           |     return f(dbname, *args, **kwargs)
> odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/http.py", line 344, in checked_call
> odoo_1           |     result = self.endpoint(*a, **kw)
> odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/http.py", line 946, in __call__
> odoo_1           |     return self.method(*args, **kw)
> odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/http.py", line 524, in response_wrap
> odoo_1           |     response = f(*args, **kw)
> odoo_1           |   File "/opt/odoo/vendor/odoo/cc/addons/web/controllers/main.py", line 966, in call_button
> odoo_1           |     action = self._call_kw(model, method, args, {})
> odoo_1           |   File "/opt/odoo/vendor/odoo/cc/addons/web/controllers/main.py", line 954, in _call_kw
> odoo_1           |     return call_kw(request.env[model], method, args, kwargs)
> odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/api.py", line 749, in call_kw
> odoo_1           |     return _call_kw_multi(method, model, args, kwargs)
> odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/api.py", line 736, in _call_kw_multi
> odoo_1           |     result = method(recs, *args, **kwargs)
> odoo_1           |   File "/opt/odoo/vendor/it-projects-llc/misc-addons/res_users_signature/models/res_users_signature_models.py", line 89, in action_update_signature
> odoo_1           |     r.action_update_signature_one()
> odoo_1           |   File "/opt/odoo/vendor/it-projects-llc/misc-addons/res_users_signature/models/res_users_signature_models.py", line 95, in action_update_signature_one
> odoo_1           |     self.user_ids.render_signature_id()
> odoo_1           |   File "/opt/odoo/vendor/it-projects-llc/misc-addons/res_users_signature/models/res_users_signature_models.py", line 34, in render_signature_id
> odoo_1           |     if not self.signature_id:
> odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/fields.py", line 979, in __get__
> odoo_1           |     record.ensure_one()
> odoo_1           |   File "/opt/odoo/vendor/odoo/cc/odoo/models.py", line 4721, in ensure_one
> odoo_1           |     raise ValueError("Expected singleton: %s" % self)
> odoo_1           | ValueError: Expected singleton: res.users(6, 2)
> ```

1) - чтобы применить подпись нужно нажать Update Signatures
2) В документации указано: войти в режим debug и редактировать в режиме "Code View"
Если вставлять напрямую в окошко, оно неявно заменяет апострофы, кавычки, <>, на разные кракозябры - поэтому программа-рендер не может обработать условные 
конструкции.
3) html-тэги работают
4) исправил- вернул декоратор api.one
5) исправил

2019-08-23 07:17 UTC, em230418 requested changes
6. Принимает `<script>alert("xss");</script>` как часть подписи. Предлагается:
- сделать список допустимых тэгов, их описать в документации. Недопустимые тэги либо экранировать или резать. В php есть метод strip_tags. Может быть в используемой нами библиотеки тоже есть
- в допустимых тэгах резать атрибуты
- `<!--` и `-->` считать недопустыми

7. Нажимаю на своего пользователя (право-верхний угол) => Preferences => Signature template. Поменяй значение на существующий (можно кликнуть на тот-же). Вылазит исключение.

8. Пункты 4, 6, 7 покрыть тестами. Примеры для 6 можно брать подобные этих https://github.com/shawarkhanethicalhacker/BruteXSS-1/blob/master/wordlist.txt

2019-08-23 08:16 UTC, KolushovAlexandr commented
4. @fedoranvar   '@api.one' is deprecated, better improve and fix new error
6. @em230418 Maybe we can rid out of scripts and comments via regexp?

2019-08-23 08:23 UTC, em230418 commented
Уточнение по 6. Я указал, что резать все атрибуты в допустимых тэгах. В исключения добавляем <img src="..."

@KolushovAlexandr, I would suggest to add whitelist of tags and attributes, and cut out everything, that is not in this list. For example `iframe` is also must not be in signature. Also, there is ping attribute for hyperlinks (https://www.w3schools.com/tags/att_a_ping.asp). Maybe in future some another tag can appear, that cannot be appeared in signature.

2019-08-23 11:47 UTC, fedoranvar commented
> 1. @fedoranvar   '@api.one' is deprecated, better improve and fix new error
> 2. @em230418 Maybe we can rid out of scripts and comments via regexp?

Without @api.one - it can't apply signature template for multiple users

2019-09-03 05:50 UTC, kaadevelop reviewed
**2 installable** modules are updated:
```
├─ res_users_signature/
|  ├─ README.rst
|  ├─ __init__.py
|  ├─ __manifest__.py
|  ├─ doc/
|  |  ├─ changelog.rst
|  |  └─ index.rst
|  ├─ images/
|  |  └─ main.png
|  ├─ models/
|  |  ├─ __init__.py
|  |  └─ res_users_signature_models.py
|  ├─ security/
|  |  └─ res_users_signature_security.xml
|  └─ views/
|     └─ res_users_signature_views.xml
└─ res_users_signature_hr/
   ├─ README.rst
   ├─ __init__.py
   ├─ __manifest__.py
   ├─ doc/
   |  └─ changelog.rst
   ├─ models/
   |  └─ res_users_signature_models.py
   └─ views.xml
```

Not installable modules remain unchanged.
```
```

> sent by [:v: Review Bot](https://odoo-devops.readthedocs.io/en/latest/git/github-review-bot.html)

2019-09-03 05:50 UTC, kaadevelop commented on res_users_signature/doc/changelog.rst
> +- **Init version**
Has to be tested

2019-09-03 05:50 UTC, kaadevelop commented on res_users_signature_hr/doc/changelog.rst
> +- **Init version**
Has to be tested

2019-10-30 07:01 UTC, em230418 commented
- http://odoo.localhost/web?debug
- Нажимаю на пользователя справа сверху, preferences
- signature template, create edit
- Переключаем на html редактирование
- <script>alert(2)</script>
- Сохраняем
- Появляется сообщение

Позже заходим по-другому
- Settings
- Users and groups
- Наш пользователь
- Preferences
- Нажимаем на наш signature template
- Появляется сообщение

2019-11-07 12:32 UTC, fedoranvar commented
>     * http://odoo.localhost/web?debug
> 
>     * Нажимаю на пользователя справа сверху, preferences
> 
>     * signature template, create edit
> 
>     * Переключаем на html редактирование
> 
>     * <script>alert(2)</script>
> 
>     * Сохраняем
> 
>     * Появляется сообщение
> 
> 
> Позже заходим по-другому
> 
>     * Settings
> 
>     * Users and groups
> 
>     * Наш пользователь
> 
>     * Preferences
> 
>     * Нажимаем на наш signature template
> 
>     * Появляется сообщение

-- Исправления: 
* Т.к. поле в которое прописывается шаблон подписи html-field, то разочек содержимое исполнится, но после Save, всё будет нормально.

например:
"<script> alert(2) </script> "  - вызовыется окошко один раз - при записи, после, (при открывании настроек юзера, например) - не откроется

2019-11-15 08:27 UTC, em230418 commented
Пример из доков не работает.
```
---

<p>${user.name}</p>

<p>% if user.phone

${user.phone},

% endif

${user.email}</p>

<p><img src="data:image/jpeg;base64,${user.company_id.logo.decode()}"/></p>
```

Потому-что % - это т.н. oneline statement. Т.е. строка должна начинаться c %. Соответственно `<p>% if user.phone` он посчитал, как просто строку, а не выражение с оператором if.

2019-11-18 08:01 UTC, fedoranvar commented
> Пример из доков не работает.
> 
> ```
> ---
> 
> <p>${user.name}</p>
> 
> <p>% if user.phone
> 
> ${user.phone},
> 
> % endif
> 
> ${user.email}</p>
> 
> <p><img src="data:image/jpeg;base64,${user.company_id.logo.decode()}"/></p>
> ```
> 
> Потому-что % - это т.н. oneline statement. Т.е. строка должна начинаться c %. Соответственно `<p>% if user.phone` он посчитал, как просто строку, а не выражение с оператором if.

Поправил пример, и добавил примечание по поводу запрещенных (не разрешенных) тэгов, и писание inline-statements'ов

2019-11-19 11:37 UTC, em230418 approved these changes

2019-11-19 11:39 UTC, em230418 commented
I approve to merge it now

2019-11-19 11:39 UTC, merged

2019-11-19 11:39 UTC, em230418 commented
https://www.youtube.com/watch?v=J8Vj7B9oE1U