:zap: add the ability to send webhooks and make instruction how to configure it
itpp-labs/misc-addons pull request #808
Opened 2019-09-02 11:46 UTC by trojikman

2019-09-02 11:46 UTC, kaadevelop reviewed
**1 installable** module is updated:
```
└─ project_timelog/
   ├─ __manifest__.py
   └─ doc/
      ├─ changelog.rst
      └─ index.rst
```

Not installable modules remain unchanged.
```
```

> sent by [:v: Review Bot](https://odoo-devops.readthedocs.io/en/latest/git/github-review-bot.html)

2019-09-02 11:46 UTC, kaadevelop commented on project_timelog/doc/changelog.rst
> +
Has to be tested

2019-09-03 11:39 UTC, yelizariev requested changes

2019-09-03 11:39 UTC, yelizariev commented on project_timelog/doc/changelog.rst
> +- Add base_automation_webhook dependency to add the ability to send webhooks
You shall not add it. It's additional optional feature

2019-09-03 11:39 UTC, yelizariev commented on project_timelog/doc/index.rst
> +Send webhooks with information when the following cases occur:
Ты написал "Отправьте вебхук когда ....". 

Напиши вначале о чем вообще раздел и чем он полезен

Допиши в инструкцию, что нужно установить модуль (дай ссылку на модуль в магазине приложений)

2019-09-03 12:48 UTC, trojikman commented on project_timelog/doc/index.rst
> +Send webhooks with information when the following cases occur:
Done

2019-09-04 10:05 UTC, yelizariev commented on project_timelog/__manifest__.py
> -        "base_automation",
![wrong](https://user-images.githubusercontent.com/186131/64246035-7d091e80-cf25-11e9-8535-b4c958578dfa.png)

2019-09-16 05:38 UTC, yelizariev requested changes
Харе закачивать кучи записей из базы

2019-09-16 05:38 UTC, yelizariev commented on project_timelog/doc/index.rst
> +`Prepare IFTTT applet <https://odoo-sync.sh/odoo2x/odoo2push-via-ifttt/documentation.html#id3>`__
The links are confusing and might be changed. Copy paste necessary part instead

2019-09-16 05:38 UTC, yelizariev commented on project_timelog/doc/index.rst
> +    * Create an Automated Action with the following values (see `Module Documentation <https://apps.odoo.com/apps/modules/10.0/base_automation_webhook/>`__ for details):
You mix links to 10 and 12

2019-09-16 05:38 UTC, yelizariev commented on project_timelog/doc/index.rst
> +            WEBHOOK = "https://maker.ifttt.com/trigger/test_event/with/key/SOME-KEY"
Event name is also custom value

2019-09-16 05:38 UTC, yelizariev commented on project_timelog/doc/index.rst
> +            base_url = env['ir.config_parameter'].get_param('web.base.url')
Did you try with non admin?

2019-09-16 05:38 UTC, yelizariev commented on project_timelog/doc/index.rst
> +            sum_time = sum(subtask.unit_amount for subtask in record.task_id.timesheet_ids)
Direct sql would work faster

2019-09-16 05:38 UTC, yelizariev commented on project_timelog/doc/index.rst
> +            duration = '%02d:%02d'%(hours, minutes)
Use timedelta class instead

2019-09-16 05:38 UTC, yelizariev commented on project_timelog/doc/index.rst
> +            elif len(timesheets) > 1 and timesheets[-2].task_id != record.task_id:
You fetch all today records. While you need just one record - previous timer of the user

2019-09-16 08:03 UTC, trojikman commented on project_timelog/doc/index.rst
> +            sum_time = sum(subtask.unit_amount for subtask in record.task_id.timesheet_ids)
There is a computed field "effective_hours" in the project.task model, which I have not noticed before. I think it would be better to use it.

2019-09-16 19:14 UTC, yelizariev requested changes
Product out of stock? Seriously?


![](https://raw.githubusercontent.com/it-projects-llc/misc-addons/f83cef114c397567d7a594fedbfe2736867a59e1/project_timelog/doc/ifttt-applet.png)

2019-09-17 11:53 UTC, yelizariev requested changes

2019-09-17 11:53 UTC, yelizariev commented on project_timelog/doc/index.rst
> +.. image:: automated_action.png
Can the example be without SOME-KEY ? You can blur private data if needed

![image](https://user-images.githubusercontent.com/186131/65039421-aa18f080-d96b-11e9-8397-7e26d6e9c328.png)

2019-09-17 11:54 UTC, trojikman commented on project_timelog/doc/index.rst
> +.. image:: automated_action.png
Ok

2019-09-17 11:54 UTC, yelizariev commented on project_timelog/doc/index.rst
> +.. image:: automated_action.png
AND WITHOUT EVENT-NAME

2019-09-17 14:10 UTC, trojikman commented on project_timelog/doc/index.rst
> +.. image:: automated_action.png
OK

2019-09-18 12:36 UTC, yelizariev commented
I approve to merge it now

2019-09-18 12:36 UTC, merged