11.0 merge from 10.0
itpp-labs/misc-addons pull request #813
Opened 2019-09-30 09:47 UTC by em230418

2019-10-06 14:04 UTC, yelizariev requested changes
If tests will work without project_timelog, we can postpone the issue https://github.com/it-projects-llc/misc-addons/issues/818

2019-10-06 14:04 UTC, yelizariev commented on project_timelog/__manifest__.py
> +    "installable": True,
Keep it disabled too

2019-10-07 06:58 UTC, em230418 commented on project_timelog/__manifest__.py
> +    "installable": True,
Done https://github.com/it-projects-llc/misc-addons/pull/813/commits/75ebb545dd73c548b76d97037fcfd75ac19d260c

2019-10-07 08:50 UTC, yelizariev commented
I approve to merge it now

2019-10-07 08:50 UTC, merged