10.0 ir attachment url ecommerce2
itpp-labs/misc-addons pull request #823
Opened 2019-10-09 12:05 UTC by em230418

2019-10-15 09:21 UTC, yelizariev commented
Comparing with original PR: https://github.com/it-projects-llc/misc-addons/compare/71c2ab8622158a690664ddf4ff4a384d8a49c4d3..2cbb659d294187c3dc091109407e6a6cc83d43cc

2019-10-15 09:58 UTC, yelizariev requested changes
* update changelogs
* kindly add your copyrights to every changed file. See https://gitlab.com/itpp/handbook/blob/master/technical-docs/copyrights.md
* Здесь я писал, что тесты не ловят какую-то ошибку. Ты разобрался? Там нужно сначала тесты исправить (чтобы ловили) и потом сам код https://github.com/it-projects-llc/misc-addons/pull/775/files#r302854688
* Тут надо код читать и разбираться. Не смотрел? Я сходу не могу понять в чем вопрос https://github.com/it-projects-llc/misc-addons/pull/775/files#r302856876
*

2019-10-15 09:58 UTC, yelizariev commented on ir_attachment_s3/controllers/main.py
> +                    print("!", image_variant_attachment)
use _logger if needed

2019-10-15 09:58 UTC, yelizariev commented on ir_attachment_s3/doc/changelog.rst
> +- **FIX:** The Odoo System parameters saving from the Environment variables removed because then we cannot change parameters through environment variables
https://github.com/it-projects-llc/misc-addons/pull/775/files#r302844946
and
https://github.com/it-projects-llc/misc-addons/pull/775/files#r302851032

2019-10-15 09:58 UTC, yelizariev commented on ir_attachment_s3/doc/changelog.rst
> +- **FIX:** The Odoo System parameters saving from the Environment variables removed because then we cannot change parameters through environment variables
The true reason why we removed it, because we don't want to have those variables in DB in travis, because it's potential way to steal the keys

2019-10-15 09:58 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +        return resized_att_id.unlink()
There was some technical reason why do we need to do it. I wanted to have explation in the comments ("why" we do something and "what")

2019-10-15 09:58 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +        return resized_ids.unlink() if resized_ids else True
Ignored: https://github.com/it-projects-llc/misc-addons/pull/775/files#r302851742

2019-10-15 09:58 UTC, yelizariev commented on ir_attachment_s3/models/res_config.py
> +        selection_add=[('s3', 'Save as a link to the file saved to s3')],
https://github.com/it-projects-llc/misc-addons/pull/775/files#r302853132 ?

2019-10-16 07:15 UTC, em230418 commented on ir_attachment_s3/models/res_config.py
> +        selection_add=[('s3', 'Save as a link to the file saved to s3')],
https://github.com/it-projects-llc/misc-addons/pull/823/commits/cda3b0a0435101af9296c87642a27f702bca5d75

2019-10-16 07:21 UTC, em230418 commented on ir_attachment_s3/models/ir_attachment.py
> +        return resized_ids.unlink() if resized_ids else True
> # to escape RecursionError, we need to check it first

Т.е. оставил `if resized_ids else True` чтобы избежать бесконечной рекурсии. А именно
- будет вызываться IrAttachmentResized.unlink, которую в свою очередь
- будет вызывать этот метод, которую в свою очередь
- будет вызываться IrAttachmentResized.unlink, которую в свою очередь

Тут соглашусь, что надо бы точки поставить, а то вторая строка как будто является продолжением предложения из первой строки. И лишнюю запятую убрать.

2019-10-16 07:25 UTC, em230418 commented on ir_attachment_s3/controllers/main.py
> +                    print("!", image_variant_attachment)
Забыл убрать

2019-10-16 10:02 UTC, em230418 commented
> Здесь я писал, что тесты не ловят какую-то ошибку. Ты разобрался? Там нужно сначала тесты исправить (чтобы ловили) и потом сам код https://github.com/it-projects-llc/misc-addons/pull/775/files#r302854688

Посмотрел еще раз. Выяснил, что вот это лишнее:
```

            if attach.res_field == 'image_medium':
                value = tools.image_resize_image(base64_source=attach.datas, size=(128, 128),
                                                 encoding='base64', filetype='PNG')
            elif attach.res_field == 'image_small':
                value = tools.image_resize_image(base64_source=attach.datas, size=(64, 64),
                                                 encoding='base64', filetype='PNG')
```
Потому-что на входе и так подается вложение с поправленым размером. Смотрел при выполнении тестов.

Вообщем убрал лишний код https://github.com/it-projects-llc/misc-addons/pull/823/commits/5cbf1ede8665a63c3a5055cbeff5aa4c4c889dce

2019-10-17 07:18 UTC, em230418 commented
> Тут надо код читать и разбираться. Не смотрел? Я сходу не могу понять в чем вопрос https://github.com/it-projects-llc/misc-addons/pull/775/files#r302856876

Если save_option не url - то сохраняет само содежимое файла в базу. Я так понял, именно этот момент надо добавить в документацию?

2019-10-17 08:17 UTC, em230418 commented
> kindly add your copyrights to every changed file

https://github.com/it-projects-llc/misc-addons/pull/823/commits/79befcc93afe42f07e037d4ef9cdadc89ca03602

2019-10-17 08:19 UTC, em230418 commented
> update changelogs

https://github.com/it-projects-llc/misc-addons/pull/823/commits/d841519caa19c5b5b9bcc99d12329dc177e742c6

2019-10-17 10:20 UTC, yelizariev commented
Consider to add changelogs to  ir_attachement_url

2019-10-17 10:24 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +        return resized_ids.unlink() if resized_ids else True
Ок, всё верно. Ты даже написал в комментарии об этом :+1:

2019-10-17 10:27 UTC, yelizariev commented
Здесь можно ТУДУ написать о том, что мы не понимаем нужно ли это или нет
https://github.com/it-projects-llc/misc-addons/pull/775/files#r335924638

2019-10-18 12:08 UTC, yelizariev reviewed
Approved in general, but let's wait for travis

2019-10-21 08:53 UTC, yelizariev commented
I approve to merge it now

2019-10-21 08:53 UTC, merged