13.0 web_website port
itpp-labs/misc-addons pull request #838
Opened 2019-10-23 07:34 UTC by em230418

2019-10-23 09:33 UTC, Ramil-Mukhametzyanov requested changes
Changing the website in the backend does not cause change website in Settings->Website->Website.
The "Go to Website" button shows only one website, regardless of the value of the switcher.

2019-10-23 09:44 UTC, Ramil-Mukhametzyanov reviewed
The errors are not due to porting to 13.0

2019-10-23 09:48 UTC, Ramil-Mukhametzyanov requested changes
"Tested on Odoo 10.0 community"

2019-10-23 10:57 UTC, Ramil-Mukhametzyanov approved these changes

2019-10-24 08:00 UTC, yelizariev requested changes

2019-10-24 08:00 UTC, yelizariev commented on web_website/models/website_dependent_mixin.py
> +        self.invalidate_cache()
Это слишком много кеша сбрасывает. Нужно попопробовать передать параметры в эту функцию и уменьшить сбрасываемый кеш. В идеале, список полей тоже можно передать -- только если поля можно вычислить без обращения к базе

2019-10-25 06:07 UTC, em230418 commented on web_website/models/website_dependent_mixin.py
> +        self.invalidate_cache()
Исправил. Список полей для сброса определаю так:
https://github.com/it-projects-llc/misc-addons/pull/838/commits/26cc3be8377d40da1fc2ac29772e07341fb5e275#diff-5b5e89289552a06231dc8dc962872c48R20

2019-10-25 11:38 UTC, yelizariev approved these changes

2019-10-28 08:26 UTC, NigmatullinAN commented
I approve to merge it now

2019-10-28 08:26 UTC, merged

2020-04-01 08:36 UTC, yelizariev commented
После установки у демо-юзера пропадает меню
![screenshot-22583-838-26cc3b-base runbot it-projects info-2020 04 01-13_35_59](https://user-images.githubusercontent.com/186131/78116467-c3701e80-741d-11ea-8a5d-aeac70b3f8cf.png)