:ambulance: TypeError: this.$buttons.find is not a function
itpp-labs/misc-addons pull request #868
Opened 2019-11-27 12:49 UTC by KolushovAlexandr

2019-12-03 15:34 UTC, yelizariev requested changes

2019-12-03 15:34 UTC, yelizariev commented on project_task_subtask/doc/changelog.rst
> +**Fix:** Compatibility issue - error on opening a task
Describe in changelog  which compatibilitiy you mean

2019-12-06 09:54 UTC, em230418 approved these changes
Кроме упомянутого https://github.com/it-projects-llc/misc-addons/pull/868#discussion_r353250004 предложений нет

2019-12-06 10:33 UTC, yelizariev commented on project_task_subtask/static/src/js/one2many_renderer.js
> +                    this.$buttons = $('<div/>');
Add a comment that it's about compatibility with multi_attachment_product_image

2019-12-07 07:44 UTC, KolushovAlexandr commented on project_task_subtask/static/src/js/one2many_renderer.js
> +                    this.$buttons = $('<div/>');
@yelizariev it's not so much about the compatibility with exact module how about proper inheritance in general. I changed the changelog so there is no notice about compatibility.

2019-12-07 10:06 UTC, yelizariev approved these changes

2019-12-19 07:09 UTC, em230418 commented
I approve to merge it now

2019-12-19 07:09 UTC, merged