12.0 ir_attachment_s3: bump version and mark as installable
itpp-labs/misc-addons pull request #869
Opened 2019-12-03 05:44 UTC by em230418

2019-12-03 11:58 UTC, yelizariev requested changes
Надо объяснить почему ты что-то делаешь. "Так будет работать" недостаточно

2019-12-03 11:58 UTC, yelizariev commented on ir_attachment_url/models/binary_fields.py
> +            return
Lines looks dangerous. Why don't use just call super in those cases?

2019-12-03 11:58 UTC, yelizariev commented on ir_attachment_url/models/ir_attachment.py
> -        url_records = self.filtered(lambda r: image.is_url(r.datas))
Why this line is not needed anymore?

2019-12-03 11:59 UTC, yelizariev commented on ir_attachment_url/models/ir_attachment.py
> -        url_records = self.filtered(lambda r: image.is_url(r.datas))
ok, I found how you implement it

2019-12-03 12:00 UTC, yelizariev commented on ir_attachment_url/models/binary_fields.py
> +        super(Binary, self).create(list(filter(lambda x: not image.is_url(x[1]), record_values)))
``self - url_records`` looks more safe

2019-12-03 12:16 UTC, em230418 commented on ir_attachment_url/models/ir_attachment.py
> -        url_records = self.filtered(lambda r: image.is_url(r.datas))
Задача - хранить вложения с ссылками так, чтобы использовалась пара {type: "url", url: ...}, а не {type: "binary", datas: ссылка}. Эту задачу можно решить двумя способами:
1. Переопределить _inverse_datas (как тут)
2. Переопределить create

Почему выбрал в итоге второй?
1. Теперь ir_attachment_s3 работает как нужно. Возьмем этот участок:
https://github.com/it-projects-llc/misc-addons/blob/1f6f598569df704fc7a6c99ecb1928858390cc17/ir_attachment_s3/models/ir_attachment.py#L118-L130
value у нас ссылка. И эту ссылку записывает как тело. Притом портит ее. Короче - ничего хорошего.
2. В методе create я понимаю зачем я записываю такие-то поля. В inverse_datas - поля checksum и index_content формируются на основе ссылки, как будто ссылка - это тело вложения.

2019-12-03 12:19 UTC, em230418 commented
> Надо объяснить почему ты что-то делаешь. "Так будет работать" недостаточно

Based on
https://github.com/odoo/odoo/blob/bba7a6b2c46320af150f34359f742ee4e0116e66/odoo/fields.py#L1853-L1872

Так сойдет?

2019-12-03 12:39 UTC, yelizariev commented
Напиши еще в чем отличии от оригинала или пометь места измененные, чтобы каждому программисту не приходилось сравнивать оригинал с измененными кодом

2019-12-03 12:41 UTC, yelizariev commented
А ты уверен, что ты не уменьшаешь область работы модуля? Что будет если просто атачмент создать, как например при отправке файла в сообщениях

2019-12-04 09:41 UTC, em230418 commented
> А ты уверен, что ты не уменьшаешь область работы модуля?

Да.

> Что будет если просто атачмент создать, как например при отправке файла в сообщениях

Создается запись ir_attachment, при общащении которого проихсодит перенаправление на файл в хранилище s3.

2019-12-04 10:07 UTC, em230418 commented
> Напиши еще в чем отличии от оригинала или пометь места измененные, чтобы каждому программисту не приходилось сравнивать оригинал с измененными кодом

Описал в комментах

https://github.com/it-projects-llc/misc-addons/pull/869/commits/758388b060dd088bf16c311ab657f71ec423b075#diff-1cee22f7e06ca6847e4dc9fcbd86bb77

2019-12-04 10:33 UTC, yelizariev commented
Это не сделал https://github.com/it-projects-llc/misc-addons/pull/869#discussion_r353137773

2019-12-04 10:39 UTC, yelizariev commented
По этому я понял теперь https://github.com/it-projects-llc/misc-addons/pull/869#issuecomment-561150190

Простой атачмент данные хранит тоже в fields.Binary

`    datas = fields.Binary(string='File Content', compute='_compute_datas', inverse='_inverse_datas')
`

При том, что Бинари создает атачмент, но с заданными полями res_field

2019-12-04 10:40 UTC, yelizariev commented
Этот комит это портирование 
https://github.com/it-projects-llc/misc-addons/pull/869/commits/17fbd097665e904590a1c46ae775e926c2e42794

2019-12-05 06:25 UTC, em230418 commented
> Это не сделал [#869 (comment)](https://github.com/it-projects-llc/misc-addons/pull/869#discussion_r353137773)

Исправил:
https://github.com/it-projects-llc/misc-addons/pull/869/files#diff-1cee22f7e06ca6847e4dc9fcbd86bb77R43-R50

2019-12-05 06:25 UTC, em230418 commented
> Этот комит это портирование (теги поменять надо)

Сменил тэг

2019-12-05 10:44 UTC, yelizariev approved these changes

2019-12-05 10:45 UTC, yelizariev commented on ir_attachment_url/models/ir_attachment.py
> -        url_records = self.filtered(lambda r: image.is_url(r.datas))
ir_attachment_url/models/ir_attachment.py:4:1: F401 '.image' imported but unused

2019-12-16 06:12 UTC, Ramil-Mukhametzyanov approved these changes

2019-12-18 08:58 UTC, em230418 commented
I approve to merge it now

2019-12-18 08:58 UTC, merged