:green_heart: pre-commit: auto cleanups
itpp-labs/misc-addons pull request #910
Opened 2020-02-08 06:20 UTC by Enigma228322

Signed-off-by: Vildan Safin <safin@it-projects.info>

2020-02-08 13:08 UTC, Enigma228322 commented on res_users_signature/res_users_signature_models.py
> +            data = body[s + len('"data:image/png;base64,') : e - 1]
Sharik goes against DINAR / pre-commit (pull_request).

2020-02-09 10:30 UTC, yelizariev requested changes
tests are broken

2020-02-09 12:27 UTC, yelizariev requested changes

2020-02-09 12:27 UTC, yelizariev commented on .pre-commit-config.yaml
> +    "--ignore=res_users.py, website_dependent_mixin.py, ir_property.py"
Сделай как 10й версии. Надо прямо в файлах указывать какую проверку отключить. 
Как ты сделал это засоряет, т.к. придется менять конфиг, если модуль будет переделан\удален. А во-вторых, ты не указал в каком модуле отключить проверку. В-третьих, ты все проверки отключил для файлов с таким именем

2020-02-09 12:28 UTC, yelizariev commented on odoo_backup_sh/__manifest__.py
> +        "data/odoo_backup_sh_data.xml",
Почему раскоментировал?

2020-02-09 12:29 UTC, yelizariev requested changes
Делай отдельные комиты для обновлений, которые автоматически сделаны и которые ты делал

2020-02-09 12:32 UTC, yelizariev commented
Ты комит назвал "auto cleanup", но там очевидно, что не всё автоматически сделано

2020-02-09 12:33 UTC, yelizariev commented
* Скопируй текущий вариант
* сделай ресет своей ветки
* запусти пре-комит
* сделай комит "авто чистка"
* скопируй сохранненый вариант файлов
* сделай комит "чистка"

2020-02-09 12:34 UTC, Enigma228322 commented on odoo_backup_sh/__manifest__.py
> +        "data/odoo_backup_sh_data.xml",
travis попросил

2020-02-09 12:35 UTC, Enigma228322 commented on odoo_backup_sh/__manifest__.py
> +        "data/odoo_backup_sh_data.xml",
> Почему раскоментировал?

travis попросил

2020-02-09 12:51 UTC, yelizariev requested changes

2020-02-09 12:51 UTC, yelizariev commented on ir_attachment_url/__manifest__.py
> -    "images": [],
Почему удалил?

2020-02-09 13:16 UTC, yelizariev commented on odoo_backup_sh/__manifest__.py
> +        "data/odoo_backup_sh_data.xml",
Откуда травис знает нужен файл или нет?

2020-02-09 13:16 UTC, yelizariev commented on reminder_task_deadline/__manifest__.py
> +    "installable": False,
Почему поменял?

2020-02-09 13:19 UTC, yelizariev commented on theme_kit/models/res_config.py
> +# Copyright 2020 Vildan Safin <https://www.it-projects.info/team/Enigma228322>
https://gitlab.com/itpp/handbook/-/blob/master/technical-docs/copyrights.md#files

2020-02-09 13:19 UTC, yelizariev commented on web_polymorphic_field/__manifest__.py
> +    "version": "11.0.0.0.0",
Сделай как в 10й, только 10 на 11 замени

2020-02-09 13:20 UTC, yelizariev commented on web_preview/controllers/controller.py
> +        id__=None,
Почему два подчеркивания?

2020-02-09 13:23 UTC, Enigma228322 commented on web_preview/controllers/controller.py
> +        id__=None,
@yelizariev случайно, через ctrl+f менял

2020-02-09 13:27 UTC, Enigma228322 commented on reminder_task_deadline/__manifest__.py
> +    "installable": False,
@yelizariev я думал он не спортирован в новую версию

2020-02-09 13:29 UTC, Enigma228322 commented on ir_attachment_url/__manifest__.py
> -    "images": [],
@yelizariev тревис ругается, что нет картинки

2020-02-09 13:30 UTC, Enigma228322 commented on odoo_backup_sh/__manifest__.py
> +        "data/odoo_backup_sh_data.xml",
@yelizariev или pre-commit, точно не помню

2020-02-09 13:50 UTC, Enigma228322 commented on odoo_backup_sh/__manifest__.py
> +        "data/odoo_backup_sh_data.xml",
@yelizariev 
![Снимок экрана от 2020-02-09 18-48-12](https://user-images.githubusercontent.com/17904007/74103327-0e338f80-4b6d-11ea-9b58-9464bb8b1bd9.png)

2020-02-09 15:21 UTC, Enigma228322 commented on odoo_backup_sh/__manifest__.py
> +        "data/odoo_backup_sh_data.xml",
Приписал в файле odoo_bachup_sh # pylint: disable=file-not-used

2020-02-09 15:23 UTC, Enigma228322 commented on .pre-commit-config.yaml
> +    "--ignore=res_users.py, website_dependent_mixin.py, ir_property.py"
@yelizariev Сделал "pylint: disable=sql-injection"

2020-02-09 15:25 UTC, Enigma228322 commented on ir_attachment_url/__manifest__.py
> -    "images": [],
@yelizariev восстановил строку "images": [],

2020-02-09 15:26 UTC, Enigma228322 commented on reminder_task_deadline/__manifest__.py
> +    "installable": False,
@yelizariev Обратно изменил на "installable": True

2020-02-09 15:26 UTC, Enigma228322 commented on theme_kit/models/res_config.py
> +# Copyright 2020 Vildan Safin <https://www.it-projects.info/team/Enigma228322>
@yelizariev удалил строку

2020-02-09 15:27 UTC, Enigma228322 commented on web_polymorphic_field/__manifest__.py
> +    "version": "11.0.0.0.0",
@yelizariev поменял "version": "11.0.1.0.2"

2020-02-09 15:28 UTC, Enigma228322 commented on web_preview/controllers/controller.py
> +        id__=None,
@yelizariev изменил на id_

2020-02-09 15:48 UTC, yelizariev commented on odoo_backup_sh/__manifest__.py
> +        "data/odoo_backup_sh_data.xml",
Ну это не значит, что его надо включать. Манифесте написано почему файл закоментирован

2020-02-09 15:57 UTC, yelizariev requested changes
Проверь на всякий, если еще отличия от 10 у тебя

2020-02-09 15:57 UTC, yelizariev commented on web_preview/controllers/controller.py
> +        id_=None,
Ты переопределеяешь встроенную функцию. Если где-нибудь она вызывается через ``content_pdf(id=123,....)``, то всё сломается. Сделай как в 10 https://github.com/it-projects-llc/misc-addons/blob/10.0/web_preview/controllers/controller.py#L2

2020-02-09 16:00 UTC, yelizariev commented
С ребейзами перестарался. Комитов Sync Dinar не должно быть

2020-02-09 17:13 UTC, Enigma228322 commented on web_preview/controllers/controller.py
> +        id_=None,
@yelizariev исправил

2020-02-10 05:35 UTC, yelizariev commented on web_website/static/src/js/switch_website_menu.js
> +            if (website === false){
Надо было местам поменять блоки
if (website)
else

2020-02-10 05:54 UTC, Enigma228322 commented on web_website/static/src/js/switch_website_menu.js
> +            if (website === false){
@yelizariev исправил

2020-02-10 06:18 UTC, Enigma228322 commented on web_preview/controllers/controller.py
> +        id_=None,
@yelizariev проверил отличия с 10, всё ровно

2020-02-10 07:48 UTC, yelizariev commented
I approve to merge it now

2020-02-10 07:48 UTC, merged