13.0 ir attachment s3 port 2020 очередная попытка
itpp-labs/misc-addons pull request #984
Opened 2020-04-17 14:17 UTC by em230418

2020-04-22 08:54 UTC, yelizariev commented
Тесты не проходят
```


odoo_1  | 2020-04-20 07:56:28,745 1 INFO DINAR odoo.addons.web_image_cache.tests.test_resized_attachments: ====================================================================== 
odoo_1  | 2020-04-20 07:56:28,745 1 ERROR DINAR odoo.addons.web_image_cache.tests.test_resized_attachments: ERROR: TestResizedAttachments.test_getting_cached_images_instead_computing
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5000, in ensure_one
odoo_1  |     _id, = self._ids
odoo_1  | ValueError: not enough values to unpack (expected 1, got 0)
odoo_1  | 
odoo_1  | During handling of the above exception, another exception occurred:
odoo_1  | 
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/opt/odoo/auto/addons/web_image_cache/tests/test_resized_attachments.py", line 54, in test_getting_cached_images_instead_computing
odoo_1  |     attachment.ensure_one()
odoo_1  |   File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5003, in ensure_one
odoo_1  |     raise ValueError("Expected singleton: %s" % self)
odoo_1  | ValueError: Expected singleton: ir.attachment()
odoo_1  |  
```

2020-04-22 11:00 UTC, em230418 commented
@yelizariev тесты исправил

2020-04-27 06:02 UTC, yelizariev commented
Линты надо исправить, иначе тесты вместе со всеми модулями не запускаются

https://github.com/itpp-labs/misc-addons/pull/984/checks?check_run_id=608247751#step:12:105

2020-04-28 06:43 UTC, yelizariev commented
Теперь тесты

`odoo_1  | Model not found: ir.attachment.config.settings
`

2020-04-28 08:43 UTC, yelizariev commented
Какие-то ошибки при совместном тестировании. Скорее всего что-то с odoo_backup_sh

```

odoo_1  | 2020-04-28 06:57:15,191 1 ERROR DINAR odoo.addons.odoo_backup_sh.tests.test_odoo_backup_sh_ui: ERROR: TestUi.test_odoo_backup_sh_tour
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/opt/odoo/auto/addons/odoo_backup_sh/tests/test_odoo_backup_sh_ui.py", line 43, in test_odoo_backup_sh_tour
odoo_1  |     login="admin",
odoo_1  |   File "/opt/odoo/custom/src/odoo/odoo/tests/common.py", line 1214, in browser_js
odoo_1  |     self.assertTrue(self.browser._wait_ready(ready), 'The ready "%s" code was always falsy' % ready)
odoo_1  |   File "/opt/odoo/custom/src/odoo/odoo/tests/common.py", line 919, in _wait_ready
odoo_1  |     res = self._get_message()
odoo_1  |   File "/opt/odoo/custom/src/odoo/odoo/tests/common.py", line 783, in _get_message
odoo_1  |     raise ChromeBrowserException(message)




odoo_1  | odoo.tests.common.ChromeBrowserException: Error while loading ir_attachment_url: TypeError: Cannot read property 'include' of undefined
odoo_1  |     at http://127.0.0.1:8069/web/content/637-6119116/web.assets_backend.js:3368:208




odoo_1  |     at http://127.0.0.1:8069/web/content/636-3c3823e/web.assets_common.js:91:297
odoo_1  |     at new Promise (<anonymous>)
odoo_1  |     at processJob (http://127.0.0.1:8069/web/content/636-3c3823e/web.assets_common.js:91:243)
odoo_1  |     at Object.odoo.processJobs (http://127.0.0.1:8069/web/content/636-3c3823e/web.assets_common.js:98:1)
odoo_1  |     at http://127.0.0.1:8069/web/content/636-3c3823e/web.assets_common.js:92:100
odoo_1  |  
```

2020-04-28 08:45 UTC, yelizariev commented
Хотя, с другими модулями может и не связано, просто за счет других модулей покрытие больше

```


odoo.define("ir_attachment_url", function(require) {
    "use strict";
    var core = require("web.core");
    var QWeb = core.qweb;
    var FieldBinaryImage = require("web.field_registry").get("image");
    var _t = core._t;

    FieldBinaryImage.include({
```

2020-04-28 11:14 UTC, em230418 commented
Спасибо Артему @ommo73 за подсказку по последней ошибке
https://github.com/itpp-labs/misc-addons/blob/88b0fd96e4f60bd52a73cf73b8531850dffbbea2/res_partner_skype/static/src/js/skype.js#L12-L16

2020-04-28 11:15 UTC, yelizariev commented on ir_attachment_s3/__manifest__.py
> +    "depends": ["base_setup", "product"],
Если эта зависимость только для тестов нужна, то лучше об этом написать комментарий в коде

2020-04-28 11:16 UTC, em230418 commented
@yelizariev вообщем сейчас при использовании кнопочки `@` будет загружаться содержимое по ссылке. Причем через сервер.

2020-04-28 11:19 UTC, em230418 commented on ir_attachment_s3/__manifest__.py
> +    "depends": ["base_setup", "product"],
Заменил этим коммитом: https://github.com/itpp-labs/misc-addons/pull/984/commits/e9fa13dee122e6e5cb70ebda60d9b699611430e4

2020-04-28 12:04 UTC, em230418 commented
Старая ветка до того, как сократил количество коммитов https://github.com/em230418/misc-addons/tree/13.0-ir_attachment_s3-port-2020-backup1

2020-04-30 12:10 UTC, yelizariev requested changes
<s>Поле Image Url скачет. Смотри видео в телеграме по запросу:

6RdaeF6ZgZhKeqIkzt5QxR5HRt3QVGbj</s>

2020-04-30 12:10 UTC, yelizariev commented on ir_attachment_url/doc/index.rst
> -* Run Odoo with ``--load=web,ir_attachment_url``
Если --load не нужно трогать, то здесь тоже надо обновить инструкцию https://github.com/itpp-labs/misc-addons/blob/4e43a75e3216dc084a685e7e6b5c401468588b41/ir_attachment_s3/doc/index.rst

2020-04-30 12:10 UTC, yelizariev commented on ir_attachment_url/doc/index.rst
> -* In filters set "URL" and custom filter "Resource Field" is set
Почему это удалено?

2020-04-30 12:10 UTC, yelizariev commented on web_image_cache/doc/index.rst
> +* `Install <https://odoo-development.readthedocs.io/en/latest/odoo/usage/install-module.html>`__ this module in a usual way
Нужна инструкция (Usage) по которой можно проверить, что модуль работает как должен

2020-04-30 12:10 UTC, yelizariev commented on ir_attachment_s3/README.rst
> +Tested on Odoo 13.0 f862f9650395b02f6a43c57cdf232a309fa6948e
В этом ридми надо из Roadmap убрать что уже сделано

2020-04-30 12:10 UTC, yelizariev commented on ir_attachment_url/doc/index.rst
> -* Go to Settings >> Technical >> Database Structure >> Attachments
Не сохраняется, если сразу нажать "Сохранить". Шаги:

* Нажать редактировать
* Нажать @ 
* Вставить ссылку
* Нажать сохранить

Результат: ничего не сохранилось

2020-04-30 12:44 UTC, yelizariev requested changes
Набор замечаний по результату изучения кода

2020-04-30 12:44 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +            and not r.name.startswith("/web/static/")
Это вообще говоря, общий код. Я думал он будет в ir_attachment_url. Иначе придется эту часть повторять во всех модуля ir_attachment_dropbox и т.п.

2020-04-30 12:44 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +                )
Add ``exc_info=True`` please

2020-04-30 12:44 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +                "url": url,
В этом цикле все кроме _file_write_s3 общее, похоже

2020-04-30 12:44 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +        file_id = "odoo/{}".format(checksum)
ТУДУ хотя бы поставь, что папку на с3 надо сделать настраиваемой или хотя бы чтобы имя базы добавлять

2020-04-30 12:44 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +            domain_part, bucket.name, file_id
Этот формат перестанет работать для бакетов созданных после сентября 2020
https://forums.aws.amazon.com/ann.jspa?annID=6776

2020-04-30 12:44 UTC, yelizariev commented on ir_attachment_s3/views/res_config_settings_views.xml
> -                                            string="Upload existing attachments"
Если ты просто удалил функционал, то так не годится

2020-04-30 12:44 UTC, yelizariev commented on ir_attachment_url/static/src/js/ir_attachment_url.js
> +                    $.get("/web/convert_url_to_base64", {
Ссылку бинарном поле можно только через интерфейс задать? Через импорт не будет работать?

2020-04-30 12:44 UTC, yelizariev commented on ir_attachment_url/models/ir_http.py
> +        # Очередной гребаный костыль
Надо еще написать почему здесь костыль (в каких случаях придется делать аналогично или когда можно будет удалить костыль)

2020-04-30 12:44 UTC, yelizariev commented on ir_attachment_url/models/ir_http.py
> +    def find_field_attachment(self, model, field, obj):
Эту функцию можно вызвать через апи и выкачать файлы без проверки доступа (у тебя судо используется), например. Надо начинать название с нижнего подчеркивания.

2020-04-30 12:44 UTC, yelizariev commented on web_image_cache/README.rst
> +This module caches resized images for faster response.
Ридми пощедрее надо сделать. Из такого описания не поймешь когда модуль может пригодится

2020-05-06 12:15 UTC, em230418 commented on ir_attachment_s3/models/ir_attachment.py
> +            and not r.name.startswith("/web/static/")
ir_attachment_url не обязателен к установке. Если перенесем туда, то без ir_attachment_url будет вьюхи на s3 загружать, что очень плохо.

2020-05-06 12:24 UTC, em230418 commented on ir_attachment_url/doc/index.rst
> -* In filters set "URL" and custom filter "Resource Field" is set
Потому-что теперь загружается содержимое из ссылок. Сама ссылка никуда не сохраняется.

2020-05-06 12:31 UTC, em230418 commented
Исправления постепенно буду загружать

2020-05-06 12:32 UTC, em230418 commented on ir_attachment_url/doc/index.rst
> -* Run Odoo with ``--load=web,ir_attachment_url``
Исправил https://github.com/itpp-labs/misc-addons/pull/984/commits/4d4da9af5be77ffdaf9024841a8e9ec4b2e0867f

2020-05-06 12:34 UTC, em230418 commented on ir_attachment_s3/README.rst
> +Tested on Odoo 13.0 f862f9650395b02f6a43c57cdf232a309fa6948e
Частично исправлено: https://github.com/itpp-labs/misc-addons/pull/984/commits/23b3ca22ec2877c25bb1243fe413c31e0267186e

2020-05-06 12:38 UTC, em230418 commented on ir_attachment_s3/models/ir_attachment.py
> +                )
Оно True по-умолчанию: https://github.com/python/cpython/blob/d64fd617e02346ecbcba9559f227936e08e89602/Lib/logging/__init__.py#L1409

2020-05-06 12:40 UTC, em230418 commented on ir_attachment_s3/models/ir_attachment.py
> +                "url": url,
Не понял

2020-05-06 12:45 UTC, em230418 commented on ir_attachment_s3/models/ir_attachment.py
> +        file_id = "odoo/{}".format(checksum)
Исправил тут 5e58dc10175f5bd18cf13bae1ca4303d7d7ede78

2020-05-06 12:58 UTC, em230418 commented on ir_attachment_url/models/ir_http.py
> +        # Очередной гребаный костыль
Уточнил a13216f0

2020-05-06 13:11 UTC, em230418 commented on ir_attachment_s3/models/ir_attachment.py
> +            domain_part, bucket.name, file_id
Исправил: https://github.com/itpp-labs/misc-addons/pull/984/commits/59df5be0c79958b429b2c7818f6a497724999e86

2020-05-06 13:20 UTC, em230418 commented on ir_attachment_s3/views/res_config_settings_views.xml
> -                                            string="Upload existing attachments"
Пользователю теперь надо через shell загружать существующие. Тут добавил уточнение: 2d0d6307

Причины переноса:
- в веб-версии не видет прогресс
- какой-нибудь nginx или envoy может тупо оборовать соединение ибо timeout.

А вообще я так понял, этот метод надо тоже скрыть нижним подчеркиванием. Я правильно понял?

2020-05-06 13:30 UTC, em230418 commented on ir_attachment_url/static/src/js/ir_attachment_url.js
> +                    $.get("/web/convert_url_to_base64", {
Ссылку в datas нельзя будет задавать. Только содержимое. Ибо получается море костылей, один из которых - пропатченный метод image_process (чтобы ссылки не трогал), что потом очень сложно портировать и в последствии поддерживать.

Притом пропатченныый image_process будет работать, если ее вызывают примерно вот так:
```
from odoo.tools import image
image.image_process(...)
```
А если ее импортировали вот так, то будет вызван оригинальный image_process
```
from odoo.tools.image import image_process
image_process(...)
```

Про импорт не понял.

2020-05-06 13:32 UTC, em230418 commented on ir_attachment_s3/README.rst
> +Tested on Odoo 13.0 f862f9650395b02f6a43c57cdf232a309fa6948e
До конца исправлено: bdf5382b

2020-05-06 16:58 UTC, yelizariev commented on ir_attachment_url/static/src/js/ir_attachment_url.js
> +                    $.get("/web/convert_url_to_base64", {
В оду есть возможность импортировать csv файл. Вопрос в том, будет ли работать если в csv ссылки указаны. Похоже, что сейчас это не поддерживается

Не видно, что где-то используется неработающий импорт

https://odoo-source.com/?q=from%20odoo.tools.image%20import%20image_process&i=nope&files=&excludeFiles=&repos=*

Кроме того, обязательно ли image_process патчить? Может пропатчить код, где он используется в оду?

2020-05-06 17:00 UTC, yelizariev commented on ir_attachment_url/static/src/js/ir_attachment_url.js
> +                    $.get("/web/convert_url_to_base64", {
Точнее так: 
Может пропатчить код, где в image_process может передаться ссылка из datas?

2020-05-07 05:20 UTC, em230418 commented on ir_attachment_url/static/src/js/ir_attachment_url.js
> +                    $.get("/web/convert_url_to_base64", {
> Не видно, что где-то используется неработающий импорт

Пардон, там немного по-другому импортируется
https://github.com/odoo/odoo/search?q=%22import+image_process%22&unscoped_q=%22import+image_process%22

В добавок, никто не исключает, что в неофициальных модулях image_process импортируется также.

> Может пропатчить код, где в image_process может передаться ссылка из datas?

Неофициальные модули так не пропатчить.

2020-05-07 05:29 UTC, em230418 commented on ir_attachment_url/static/src/js/ir_attachment_url.js
> +                    $.get("/web/convert_url_to_base64", {
> В оду есть возможность импортировать csv файл. Вопрос в том, будет ли работать если в csv ссылки указаны. Похоже, что сейчас это не поддерживается

Смотря, что подавать на входе.
- Если type=url, url=ссылка, то вангую тут и без нашего модуля можно обойтись. Ссылки как и раньше ссылками будут.
- Если datas = ссылка, то ничего хорошего не будет.

2020-05-07 06:11 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +            and not r.name.startswith("/web/static/")
Добавь юрл в зависимости или сделай другой общий модуль

2020-05-07 06:13 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +                "url": url,
Я говорю, что куча кода общего для модулей типа ir_attachment_dropbox. 
Это замечание связано с эти https://github.com/itpp-labs/misc-addons/pull/984#discussion_r417967157

2020-05-07 06:15 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +        obj = bucket.put_object(  # noqa: F841
Почему отключил линты?

2020-05-07 06:18 UTC, yelizariev commented on ir_attachment_s3/views/res_config_settings_views.xml
> -                                            string="Upload existing attachments"
Комментарий в документации полезный, но может не всем подойти. Например, нет доступа в консоль или слишком сложно туда заходить. Проблемы, о которых ты говоришь известны, но они не мешают сделать загрузку, хоть и вслепую

2020-05-07 06:33 UTC, yelizariev commented on ir_attachment_url/static/src/js/ir_attachment_url.js
> +                    $.get("/web/convert_url_to_base64", {
> Неофициальные модули так не пропатчить.

Мы можем написать о возможной несовместимости в ридми. Но в данном случае, если кто-то использует image_process, то туда скорее всего передается картинка, а не ссылка. Кроме того, даже если туда попадет ссылка, то такой модуль легко исправить заменив импорт.

Про официальные модули. Там всего три примера, [как я понял](https://odoo-source.com/?q=from.*image_process&i=nope&files=&excludeFiles=&repos=)

1. Контроллер /web/image https://github.com/odoo/odoo/blob/c8217080d960ec3f8436111ce60a17754fe64f2d/addons/web/controllers/main.py#L1459

-- он с самого начала копи-пастом у нас патчился. Всё что мы можем сейчас сделать это отправить ПР в оду мастер, чтобы потом можно было легче расширять или патчить.

2. purchase/controllers/portal.py https://github.com/odoo/odoo/blob/054d4bc6bc219bcc6b0a64265e8d7e9c7423dbc8/addons/purchase/controllers/portal.py

-- здесь надо целиком патчить _purchase_order_get_page_view_values. Можно в ридми просто туду написать о возможных проблемах при использовании портала в модуле покупок

3. payment.icon https://github.com/odoo/odoo/blob/4b12643abc6b8ba34f14e468e8d7760bc2db385b/addons/payment/models/payment_acquirer.py#L528-L542

Довольно специфический случай. Маловероятно, что туда ссылка попадет.

2020-05-07 06:34 UTC, yelizariev commented on ir_attachment_url/static/src/js/ir_attachment_url.js
> +                    $.get("/web/convert_url_to_base64", {
> В оду есть возможность импортировать csv файл. Вопрос в том, будет ли работать если в csv ссылки указаны. Похоже, что сейчас это не поддерживается

Речь о бинарных полях с картинками или просто файлами

2020-05-07 07:00 UTC, yelizariev commented on ir_attachment_url/static/src/js/ir_attachment_url.js
> +                    $.get("/web/convert_url_to_base64", {
Нужен либо еще один костыль для импорта либо вернуть возможность задавать ссылку в поле.

Например, у кого-нибудь есть 1000 продуктов с картинками на cdn. Эти продукты сейчас невозможно без лишних усилий импортировать в оду

2020-05-07 07:02 UTC, yelizariev commented on ir_attachment_url/static/src/js/ir_attachment_url.js
> +                    $.get("/web/convert_url_to_base64", {
Да и сам костыль для картинок переделать надо -- у меня есть ссылка на крутой cdn, а модуль выкачивает его и сохраняет (на с3 или по обычному)

2020-05-07 07:35 UTC, em230418 commented
> > Неофициальные модули так не пропатчить.
> 
> Мы можем написать о возможной несовместимости в ридми. Но в данном случае, если кто-то использует image_process, то туда скорее всего передается картинка, а не ссылка. Кроме того, даже если туда попадет ссылка, то такой модуль легко исправить заменив импорт.
> 

> Про официальные модули. Там всего три примера, [как я понял](https://odoo-source.com/?q=from.*image_process&i=nope&files=&excludeFiles=&repos=)
> 
> 1. Контроллер /web/image https://github.com/odoo/odoo/blob/c8217080d960ec3f8436111ce60a17754fe64f2d/addons/web/controllers/main.py#L1459
> 
> -- он с самого начала копи-пастом у нас патчился. Всё что мы можем сейчас сделать это отправить ПР в оду мастер, чтобы потом можно было легче расширять или патчить.
> 

Костылем был с самого начала.

> 2. purchase/controllers/portal.py https://github.com/odoo/odoo/blob/054d4bc6bc219bcc6b0a64265e8d7e9c7423dbc8/addons/purchase/controllers/portal.py
> 
> -- здесь надо целиком патчить _purchase_order_get_page_view_values. Можно в ридми просто туду написать о возможных проблемах при использовании портала в модуле покупок
> 

Т.е. предлагается еще тут костылить и написать в ридми "у при установки ir_attachment_url у Вас могут быть проблемы при использовании портала в модуле покупок".

> 3. payment.icon https://github.com/odoo/odoo/blob/4b12643abc6b8ba34f14e468e8d7760bc2db385b/addons/payment/models/payment_acquirer.py#L528-L542
> 
> Довольно специфический случай. Маловероятно, что туда ссылка попадет.
> 

Пусть будет так.

Помимо этого еще есть такая фигня:
https://github.com/odoo/odoo/blob/054d4bc6bc219bcc6b0a64265e8d7e9c7423dbc8/odoo/addons/base/models/image_mixin.py

В страничке в бэкенде для поля image_1920 задаем ссылку. Поскольку остальные поля related, они вычисляются вот тут:
https://github.com/odoo/odoo/blob/119ebbc727d7d95caa6d8812299bbc53540a59e8/odoo/fields.py#L2077-L2084

Что остальных полей можно сделать? Можно заранее скачать содержимое с помощью requests.get передать в оригинальный image_process.
В итоге image_1920 будет ссылкой, а остальные image_* - бинарники.

---

Еще есть такой метод:
https://github.com/odoo/odoo/blob/4b12643abc6b8ba34f14e468e8d7760bc2db385b/odoo/tools/image.py#L427-L438

Применения в официальных модуля:
https://github.com/odoo/odoo/blob/9d5d80f77bc04be83d5b2ca0569a6ea50e26a07e/addons/product/models/product_template.py#L164
https://github.com/odoo/odoo/blob/77e5472c041efb787af9ef9c31814608d22c8b18/addons/product/models/product.py#L145
https://github.com/odoo/odoo/blob/054d4bc6bc219bcc6b0a64265e8d7e9c7423dbc8/addons/website_sale/models/product_image.py#L32

Возвращать True или False без обращения по ссылке - не годиться. Тут надо обращаться по ссылке и в итоге получаем ситуацию, когда лучше бинарник, чем ссылка.
Напоминает это https://github.com/odoo/odoo/issues/49762 но на этот раз это косяк нашего модуля.

---

Это были моменты, которые я запомнил с какой проблемой сталкивался, когда я несколько раз пытался портировать ir_attachent_* в 13.0 в 2019 году без кардинального переписывания оригинала.
Это все растянулось до сегодняшнего момента. Появится оду 14.0 и будет костыли портировать пока не появится оду 15.0.

Короче - нафиг ссылки в datas. Только содержимое.

2020-05-07 07:42 UTC, em230418 commented on ir_attachment_url/static/src/js/ir_attachment_url.js
> +                    $.get("/web/convert_url_to_base64", {
> > Неофициальные модули так не пропатчить.
> 
> Мы можем написать о возможной несовместимости в ридми. Но в данном случае, если кто-то использует image_process, то туда скорее всего передается картинка, а не ссылка. Кроме того, даже если туда попадет ссылка, то такой модуль легко исправить заменив импорт.
> 

> Про официальные модули. Там всего три примера, [как я понял](https://odoo-source.com/?q=from.*image_process&i=nope&files=&excludeFiles=&repos=)
> 
> 1. Контроллер /web/image https://github.com/odoo/odoo/blob/c8217080d960ec3f8436111ce60a17754fe64f2d/addons/web/controllers/main.py#L1459
> 
> -- он с самого начала копи-пастом у нас патчился. Всё что мы можем сейчас сделать это отправить ПР в оду мастер, чтобы потом можно было легче расширять или патчить.
> 

Костылем был с самого начала.

> 2. purchase/controllers/portal.py https://github.com/odoo/odoo/blob/054d4bc6bc219bcc6b0a64265e8d7e9c7423dbc8/addons/purchase/controllers/portal.py
> 
> -- здесь надо целиком патчить _purchase_order_get_page_view_values. Можно в ридми просто туду написать о возможных проблемах при использовании портала в модуле покупок
> 

Т.е. предлагается еще тут костылить и написать в ридми "у при установки ir_attachment_url у Вас могут быть проблемы при использовании портала в модуле покупок".

> 3. payment.icon https://github.com/odoo/odoo/blob/4b12643abc6b8ba34f14e468e8d7760bc2db385b/addons/payment/models/payment_acquirer.py#L528-L542
> 
> Довольно специфический случай. Маловероятно, что туда ссылка попадет.
> 

Пусть будет так.

Помимо этого еще есть такая фигня:
https://github.com/odoo/odoo/blob/054d4bc6bc219bcc6b0a64265e8d7e9c7423dbc8/odoo/addons/base/models/image_mixin.py

В страничке в бэкенде для поля image_1920 задаем ссылку. Поскольку остальные поля related, они вычисляются вот тут:
https://github.com/odoo/odoo/blob/119ebbc727d7d95caa6d8812299bbc53540a59e8/odoo/fields.py#L2077-L2084

Что остальных полей можно сделать? Можно заранее скачать содержимое с помощью requests.get передать в оригинальный image_process.
В итоге image_1920 будет ссылкой, а остальные image_* - бинарники.

---

Еще есть такой метод:
https://github.com/odoo/odoo/blob/4b12643abc6b8ba34f14e468e8d7760bc2db385b/odoo/tools/image.py#L427-L438

Применения в официальных модуля:
https://github.com/odoo/odoo/blob/9d5d80f77bc04be83d5b2ca0569a6ea50e26a07e/addons/product/models/product_template.py#L164
https://github.com/odoo/odoo/blob/77e5472c041efb787af9ef9c31814608d22c8b18/addons/product/models/product.py#L145
https://github.com/odoo/odoo/blob/054d4bc6bc219bcc6b0a64265e8d7e9c7423dbc8/addons/website_sale/models/product_image.py#L32

Возвращать True или False без обращения по ссылке - не годиться. Тут надо обращаться по ссылке и в итоге получаем ситуацию, когда лучше бинарник, чем ссылка.
Напоминает это https://github.com/odoo/odoo/issues/49762 но на этот раз это косяк нашего модуля.

---

Это были моменты, которые я запомнил с какой проблемой сталкивался, когда я несколько раз пытался портировать ir_attachent_* в 13.0 в 2019 году без кардинального переписывания оригинала.
Это все растянулось до сегодняшнего момента. Появится оду 14.0 и будет костыли портировать пока не появится оду 15.0.

Короче - нафиг ссылки в datas. Только содержимое.

2020-05-07 07:42 UTC, yelizariev commented
> В итоге image_1920 будет ссылкой, а остальные image_* - бинарники.

Это ведь если только web_image_cache не установлен? Пускай так и будет

2020-05-07 07:45 UTC, yelizariev commented
> Короче - нафиг ссылки в datas. Только содержимое.

Подумаю

2020-05-07 07:50 UTC, em230418 commented on ir_attachment_url/static/src/js/ir_attachment_url.js
> +                    $.get("/web/convert_url_to_base64", {
> Нужен либо еще один костыль для импорта либо вернуть возможность задавать ссылку в поле.

Можно ссылку хранить в поле url, а не datas. Но как я уже выше писал про поля из image_mixin, содержимое по ссылке все равно придется скачивать.

2020-05-07 07:53 UTC, em230418 commented on ir_attachment_s3/models/ir_attachment.py
> +        obj = bucket.put_object(  # noqa: F841
F841 - неиспользуема переменная. Могу удалить переменную.

2020-05-07 07:55 UTC, yelizariev commented
Убедил. Ссылки в бинарные поля не передаем. Я думаю тогда редактирование через `@` вообще удалить: куча багов, а по функционалу это эквиваленту скачиванию ссылку и загрузки через браузер обычным способом.

2020-05-07 07:55 UTC, em230418 commented on ir_attachment_s3/views/res_config_settings_views.xml
> -                                            string="Upload existing attachments"
Тогда верну то, что было, но метод с консолью оставлю.

2020-05-07 07:59 UTC, em230418 commented
> Это ведь если только web_image_cache не установлен?

Нет. web_image_cache полезен, когда идет обращение к /web/image с параметрами width, heigh которые могут иметь произвольные значения.

2020-05-07 07:59 UTC, yelizariev commented on ir_attachment_url/doc/index.rst
> -* In filters set "URL" and custom filter "Resource Field" is set
Надо какой-то Usage прописать о том как вручную проверить модуль (через атачменты картинку где-нибудь задать и открыть 301 через /web/image .... ?)

2020-05-07 08:00 UTC, yelizariev commented on ir_attachment_url/doc/index.rst
> -* Go to Settings >> Technical >> Database Structure >> Attachments
Функцию задания ссылки удаляем

2020-05-07 08:00 UTC, em230418 commented
> Я думаю тогда редактирование через @

Согласен.

2020-05-07 08:01 UTC, yelizariev commented on ir_attachment_url/static/src/js/ir_attachment_url.js
> +                    $.get("/web/convert_url_to_base64", {
Функцию задания ссылки удаляем

2020-05-07 08:11 UTC, yelizariev commented on ir_attachment_s3/__manifest__.py
> +        "product",  # Note: product dependency is for unittests only
Надо ir_attachment_url. Иначе получится, что модуль с3 позволяет картинки в ссылки превратить и такие картинки перестанут открываться

2020-05-07 08:31 UTC, em230418 commented on ir_attachment_s3/__manifest__.py
> +        "product",  # Note: product dependency is for unittests only
Пожалуй соглашусь

2020-05-07 08:33 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +        obj = bucket.put_object(  # noqa: F841
Лучше переменную удалять

2020-05-07 11:07 UTC, em230418 commented on ir_attachment_url/models/ir_http.py
> +    def find_field_attachment(self, model, field, obj):
Обернул как classmethod 29e23ee8ebf6e1cb1a4b2cbc4a448c9b1e1134a4

2020-05-07 11:08 UTC, em230418 commented on ir_attachment_s3/models/ir_attachment.py
> +        obj = bucket.put_object(  # noqa: F841
Исправил: 5ab4afa2ab89678cebfbdd0f7b628cf8acafade1

2020-05-07 11:09 UTC, em230418 commented on ir_attachment_s3/__manifest__.py
> +        "product",  # Note: product dependency is for unittests only
Исправил 1c92b7107

2020-05-07 11:10 UTC, em230418 commented on ir_attachment_s3/models/ir_attachment.py
> +            and not r.name.startswith("/web/static/")
1c92b7107 и 27f39bf67a9d1925afcaca3630df70e51b564cf6

2020-05-25 06:23 UTC, yelizariev commented on ir_attachment_url/models/binary_fields.py
> -                                "type": "url",
Может эти функции в каком-то виде оставить, чтобы в виде АПИ как-то использовать хотя бы? Типа, если есть контекст специальный, то создавать эти несчастные атачменты? Может даже не на уровне odoo.fields это оставить, а в метод create, write засунуть? Примерно так:

* ``_inherit = 'base'`` https://odoo-source.com/?q=_inherit%20%3D%20.base.%24&i=nope&files=&excludeFiles=po%24%7Cpot%24&repos=13.0
* Далее переопределить метод write, create, которые проверяют контекст, скажем ``ir_attachment_url_fields``, где через запятую перечисленны поля, в которых вместо бинарных значений используются ссылки
* Далее, эти поля убираем из vals, вызываем супер, создаем атачменты

2020-05-26 06:18 UTC, em230418 commented on ir_attachment_url/models/binary_fields.py
> -                                "type": "url",
Я понял так. Надо переопределить метод create на `ir.attachment`. С контекстом `ir_attachment_url_fields` то, что дали по datas считать как ссылку, соответственно оттуда загружать c помощью `requests.get` и перезаписать значение datas. Ну и может быть ссылку вставить в поле url, правда тут я не знаю, что будет.

Я правильно понял?

2020-05-27 07:30 UTC, yelizariev commented on ir_attachment_url/models/binary_fields.py
> -                                "type": "url",
* Не атачменты , а base. Тогда это ко всем моделям применится.
* requests.get не надо использовать. Посмотри мое сообщения - я алгоритм подробно написал

Держи в уме такой пример:

* нужно через апи создать запись со ссылкой в этом поле https://github.com/odoo/odoo/blob/23511dffb9e3f597a7df9bb834d008f74abb07b8/addons/mrp/models/mrp_routing.py#L53
* при этом сервер на должен загружать файл
* модули типа с3 не используются

2020-06-01 10:55 UTC, em230418 commented on ir_attachment_url/models/binary_fields.py
> -                                "type": "url",
https://github.com/itpp-labs/misc-addons/pull/984/commits/0a09fb276eda1816c497d6e3f94e1f1dafd1274b

Это сделать предполагалось?

2020-06-01 12:08 UTC, yelizariev commented on ir_attachment_url/models/binary_fields.py
> -                                "type": "url",
Выглядит опасным

            self._fields[fname].__class__ = MyBinary

Почему ты буквально по моему алгоритму не сделаешь? Просто _inherit = _base сделать без дополнительных классов не трогая классы полей

2020-06-01 13:03 UTC, em230418 commented on ir_attachment_url/models/binary_fields.py
> -                                "type": "url",
Переделал согласно этому пункту:
> Далее, эти поля убираем из vals, вызываем супер, создаем атачменты

https://github.com/itpp-labs/misc-addons/pull/984/commits/738d161ad803c2675ff369dc4d6092bd41eb9b73



> Почему ты буквально по моему алгоритму не сделаешь?

Хотел, чтобы `super(Base, self).write(vals)` записывал все, что нужно ибо предназначен для этого.

2020-06-02 04:56 UTC, yelizariev requested changes
<s>ir_attachment_url_fields надо еще для create сделать</s>

2020-06-02 04:56 UTC, yelizariev commented on ir_attachment_url/tests/test_attachment_fields.py
> +        self.assertEqual(test_record.image, bytes(test_url, "utf-8"))
В чем смысл такой проверки? Модуль вроде содержание файла должен отдавать при чтении таких полей? Я так понимаю здесь проверка работает только из-за того, что значение из кеша берется, а не по обычному механизму вычисляется

2020-06-02 04:56 UTC, yelizariev commented on ir_attachment_url/models/base.py
> +        url_fields = self.env.context.get("ir_attachment_url_fields", "").split(",")
Надо в index.rst пример использования какой-то показать насчет этого контекста

2020-06-02 04:57 UTC, yelizariev commented on ir_attachment_url/models/binary_fields.py
> -                                "type": "url",
Может и правильно у тебя было, но слишком сложно читать и понимать.

Замечания отправил сюда: https://github.com/itpp-labs/misc-addons/pull/984#pullrequestreview-422341503

2020-06-02 07:26 UTC, em230418 commented on ir_attachment_url/tests/test_attachment_fields.py
> +        self.assertEqual(test_record.image, bytes(test_url, "utf-8"))
Слегка переделал тест и код 9dd5381e67453483e4fecf4d5a17dc8c550a4fcd

> В чем смысл такой проверки?

Задача - сделать так, чтобы можно было ссылку задавать со специальным контекстом.
И также продемонстировать, что без нашего контекста и со сброшеным кэшем будет выдаваться то, что обычно выдается (значение поля datas в ir.attachment).

В первом assertRaises проверяется, что пример с ссылкой без специального контекста вызывает исключение (сталкивался с некоторыми примерами, при котором почему-то не вызывает).

> Модуль вроде содержание файла должен отдавать при чтении таких полей? 

Если у атачмента поле type = binary, то отдает содержимое из поле datas (стандартное поведение) или ссылку, если указано в поле url (поведение при ir_attachment_url). Такого теста тут нет.

Но с помощью контекста `ir_attachment_url_fields` и метода `my_write` мы создаем аттачменты с полем type = url и значением в поле url. Далее с этим-же контесктом читаем поле по-другому (не поле datas, а url).

> Я так понимаю здесь проверка работает только из-за того, что значение из кеша берется

Тут кстати верно. Так работало до упомянутого коммита. После этого коммита также демострируется вариант со сброшеным кэшем.

2020-06-02 08:32 UTC, em230418 commented on ir_attachment_url/models/base.py
> +        url_fields = self.env.context.get("ir_attachment_url_fields", "").split(",")
Можно на тесты сослаться? "См. test_write и test_create". Текущий test_main - это будущий test_write.

2020-06-04 08:03 UTC, yelizariev commented on ir_attachment_url/models/base.py
> +        url_fields = self.env.context.get("ir_attachment_url_fields", "").split(",")
Да, хотя бы. В виде ссылке на файл только

2020-06-04 08:20 UTC, yelizariev commented on ir_attachment_url/models/base.py
> +        url_fields = self.env.context.get("ir_attachment_url_fields", "").split(",")
Хотя нет, по тестам не понятно. Там с точками конструкция какая-то

2020-06-04 08:23 UTC, yelizariev commented on ir_attachment_url/tests/test_attachment_fields.py
> +        self.assertEqual(test_record.image, bytes(test_url, "utf-8"))
```
        test_record = self.env["res.country"].browse(test_record.id)
        test_record.invalidate_cache(fnames=["image"])
        self.assertEqual(test_record.image, False)
```

Почему здесь False? Вроде должен ссылку скачать и выдать?

2020-06-04 10:37 UTC, em230418 commented on ir_attachment_url/tests/test_attachment_fields.py
> +        self.assertEqual(test_record.image, bytes(test_url, "utf-8"))
> Почему здесь False? Вроде должен ссылку скачать и выдать?

Забыл вернуть соответствующий функционал. cbc6a8c4dd09fb4027dacaa3cb4f22c2476866a8 и https://github.com/itpp-labs/misc-addons/pull/984/commits/90b6f783503fce9afa97d0950c693e2c96293c9d

2020-06-04 11:46 UTC, em230418 commented on ir_attachment_url/models/base.py
> +        url_fields = self.env.context.get("ir_attachment_url_fields", "").split(",")
Сейчас устроит? В итоге ссылаюсь на тесты, но пояснил за точки.

2020-06-04 12:19 UTC, em230418 commented on ir_attachment_s3/views/res_config_settings_views.xml
> -                                            string="Upload existing attachments"
Через веб интерфейс вернул a19a9bee4ea95582836f57020ed85c521c5fc869 и доки исправил f4bc4d87277fd0e71f785cb38ad82040ea12d5b0

2020-06-05 07:14 UTC, yelizariev commented on ir_attachment_url/models/base.py
> +        url_fields = self.env.context.get("ir_attachment_url_fields", "").split(",")
@trojikman потом еще глянет

2020-06-10 10:41 UTC, em230418 commented on ir_attachment_url/doc/index.rst
> +* You will see address will change from odoo's url to url where file is hosted. For example, if you are using ir_attachment_s3, host will change to *.s3.amazonaws.com
В продолжения этой темы: https://github.com/itpp-labs/misc-addons/pull/984/files#r417956731

Так сойдет?

2020-06-10 10:46 UTC, em230418 commented on ir_attachment_s3/models/ir_attachment.py
> +                "url": url,
Перенес некоторые методы в ir_attachment_url

2020-06-10 10:48 UTC, em230418 commented
> ir_attachment_url_fields надо еще для create сделать

Сделал.

2020-06-10 10:49 UTC, em230418 commented on ir_attachment_url/models/binary_fields.py
> -                                "type": "url",
Вообщем-то переписал. Результат в `base.py`

2020-06-10 11:18 UTC, em230418 commented on web_image_cache/README.rst
> +This module caches resized images for faster response.
Так сойдет? https://github.com/itpp-labs/misc-addons/pull/984/commits/c037a1f9a47603dd88460090eb5649d4a4b2effd

2020-06-10 11:20 UTC, em230418 commented on ir_attachment_url/doc/index.rst
> -* In filters set "URL" and custom filter "Resource Field" is set
Продолжение: https://github.com/itpp-labs/misc-addons/pull/984/files#discussion_r438029077

2020-06-10 14:16 UTC, em230418 commented on web_image_cache/doc/index.rst
> +* `Install <https://odoo-development.readthedocs.io/en/latest/odoo/usage/install-module.html>`__ this module in a usual way
Пока приходит в голову такая идея, как проверять работоспособность.
Выполняем запросы вида:
http://odoo.localhost/web/image?model=res.users&field=image_128&id=2&width=110&height=110
http://odoo.localhost/web/image?model=res.users&field=image_128&id=2&width=120&height=120
http://odoo.localhost/web/image?model=res.users&field=image_128&id=2&width=130&height=130
http://odoo.localhost/web/image?model=res.users&field=image_128&id=2&width=140&height=140

Далее в Settings -> Technical -> Attachments видим созданные аттачменты.

Так сойдет?

2020-06-11 07:41 UTC, yelizariev commented on ir_attachment_url/doc/index.rst
> +* You will see address will change from odoo's url to url where file is hosted. For example, if you are using ir_attachment_s3, host will change to *.s3.amazonaws.com
Можешь без с3 сценарий сделать? Вручную ведь можно картинку задать через меню атачменты

2020-06-11 07:48 UTC, yelizariev commented on web_image_cache/doc/index.rst
> +* `Install <https://odoo-development.readthedocs.io/en/latest/odoo/usage/install-module.html>`__ this module in a usual way
Да

2020-06-11 07:52 UTC, yelizariev commented on ir_attachment_s3/models/ir_attachment.py
> +                "url": url,
Ок, имена только остались привязаны к с3. ПРимер: _get_datas_related_values_with_bucket

вместо бакета может storage?

2020-06-11 07:53 UTC, yelizariev commented on web_image_cache/README.rst
> +This module caches resized images for faster response.
Да, отлично

2020-06-11 08:08 UTC, em230418 commented on ir_attachment_s3/models/ir_attachment.py
> +                "url": url,
В Google Cloud Storage (не путать с Google Drive), там также есть такая вещь как bucket.
https://cloud.google.com/storage/docs/creating-buckets

Т.е. имена не привязаны к терминологии s3.

2020-07-14 09:57 UTC, em230418 commented on ir_attachment_url/doc/index.rst
> +* You will see address will change from odoo's url to url where file is hosted. For example, if you are using ir_attachment_s3, host will change to *.s3.amazonaws.com
Сделал: https://github.com/itpp-labs/misc-addons/pull/984/commits/3784d258e35b30cd6258979f64931367877cbb2f

2020-07-15 07:49 UTC, em230418 commented
Было 53 коммита, стало 9

2020-07-20 07:21 UTC, yelizariev approved these changes
Предыдущие замечания исправлены

2020-07-22 12:15 UTC, trojikman commented
Судя по всему устарела ссылка
https://github.com/itpp-labs/misc-addons/blob/db657dd01626a337113aca525cf419eda6a820a3/ir_attachment_s3/doc/index.rst#L9

При беглом поиске нашел такое https://aws.amazon.com/ru/premiumsupport/knowledge-center/s3-console-access-certain-bucket/
@yelizariev подходит такая интструкция?

2020-07-22 12:42 UTC, trojikman commented on ir_attachment_s3/doc/index.rst
>  * Open menu ``Settings >> Parameters >> System Parameters`` and specify the following parameters there
```sugestion
* Open menu ``Settings >> Technical >> Parameters >> System Parameters`` and specify the following parameters there
```

2020-07-22 16:24 UTC, trojikman reviewed
Настроил вроде как надо, заметил вот такое:
1) Меняю картинку у этого продукта
![1](https://user-images.githubusercontent.com/23641186/88201741-47664480-cc61-11ea-8a54-7db12c3511f4.png)
2) На с3 всё улетает как надо.
![2](https://user-images.githubusercontent.com/23641186/88201798-5b11ab00-cc61-11ea-85e3-e31020f7fbf6.png)
3) Выхожу назад, обновляю страницу, а картинка тут не поменялась
![3](https://user-images.githubusercontent.com/23641186/88201930-8c8a7680-cc61-11ea-840f-7bd85bf7040e.png)

Обратно вхожу в этот продукт, там всё как надо

2020-07-23 10:46 UTC, em230418 commented
> Настроил вроде как надо, заметил вот такое:
> 
>     1. Меняю картинку у этого продукта
> 
>     2. На с3 всё улетает как надо.
> 
>     3. Выхожу назад, обновляю страницу, а картинка тут не поменялась
> 
> 
> Обратно вхожу в этот продукт, там всё как надо

Добавил в roadmap следующей строкой:

> In backend. Set product image as binary file (s3), in product page it shows new image, in product list it shows old image. Reason: there is no 'unique' parameter in image source attribute (<img src)

Пунктом выше также описана проблема с той-же причиной "Reason: there is no 'unique' parameter in image source attribute (<img src)"

Ну и в добавок исправил косяк, когда не задав до конца (или вообще не задав) логин-пароли-корзины для S3 может вылести такая лабуда:

```
odoo_1   |   File "/mnt/addons/misc-addons/ir_attachment_s3/models/ir_attachment.py", line 61, in _inverse_datas
odoo_1   |     s3_records._write_records_with_bucket(bucket)
odoo_1   | odoo.tools.convert.ParseError: "local variable 'bucket' referenced before assignment"
```

2020-07-24 06:54 UTC, yelizariev commented
@em230418 может в ссылку добавлять ``"URL.....?%s" % write_date``

2020-07-24 11:07 UTC, yelizariev commented on web_image_cache/controllers/main.py
> +    def _content_image(self, **kw):
Обычно при наследовании вставляют пустой роутер

https://odoo-source.com/?q=%40.*route%5C(%5C)&i=nope&files=&excludeFiles=po%24%7Cpot%24%7Cyml%24%7Cyaml%24%7Ccss%24%7C%2Fstatic%2Flib%2F&repos=13.0

2020-07-24 11:18 UTC, em230418 commented on web_image_cache/controllers/main.py
> +    def _content_image(self, **kw):
Родительский метод без роутера. https://github.com/odoo/odoo/blob/96119d71a132e13a1fb4e6e3ebdb04c24c7430fe/addons/web/controllers/main.py#L1439

2020-07-24 12:34 UTC, yelizariev commented on web_image_cache/controllers/main.py
> +    def _content_image(self, **kw):
А, ок. Спутал с content_image

2020-07-24 12:35 UTC, yelizariev commented
Пока ждем решение с использованием кода 302

2020-07-24 13:16 UTC, yelizariev approved these changes
Надо ридми проверить и удалить проблемы, которые исправлены

2020-08-01 09:25 UTC, trojikman reviewed
Получаю такое сообщение, когда оставляю поле S3 condition пустым
![1](https://user-images.githubusercontent.com/23641186/89098618-a4e95680-d402-11ea-93e5-4c2f22d81e12.png)

2020-08-07 11:42 UTC, em230418 commented
> Получаю такое сообщение, когда оставляю поле S3 condition пустым

@trojikman  такое сообщение появляется, если нажать на Upload Existing Attachments. У тебя не заполнены s3 bucket name, s3 access key и s3 secret key, и по этой причине данное сообщение появляется.

2020-08-07 11:43 UTC, em230418 commented
> > Получаю такое сообщение, когда оставляю поле S3 condition пустым
> 
> @trojikman такое сообщение появляется, если нажать на Upload Existing Attachments. У тебя не заполнены s3 bucket name, s3 access key и s3 secret key, и по этой причине данное сообщение появляется.

Ибо тут непонятно, как на s3 загружать если логин-пароли не заданы

2020-08-07 23:00 UTC, trojikman commented on ir_attachment_s3/models/res_config_settings.py
> +        if not access_key_id or not secret_key or not bucket_name:
`bucket_name` тут, как я понимаю, лишний, потому что в случае когда корзина не создана до этого места доходить не будет:
https://github.com/itpp-labs/misc-addons/blob/e3c4d32451d6cf957fce91f6db4412cfc6584205/ir_attachment_s3/models/res_config_settings.py#L49-L52

2020-08-08 11:05 UTC, trojikman commented
> > Получаю такое сообщение, когда оставляю поле S3 condition пустым
> 
> @trojikman такое сообщение появляется, если нажать на Upload Existing Attachments. У тебя не заполнены s3 bucket name, s3 access key и s3 secret key, и по этой причине данное сообщение появляется.

Речь как раз о том, что я заполнил все поля кроме "condition"

2020-08-08 11:59 UTC, trojikman requested changes

2020-08-08 11:59 UTC, trojikman commented on ir_attachment_s3/models/res_config_settings.py
> +        bucket = s3.Bucket(bucket_name)
Вернет True, даже если bucket не создан, поэтому условие ниже не сработает как надо

2020-08-08 12:27 UTC, yelizariev commented on ir_attachment_s3/models/res_config_settings.py
> +        bucket = s3.Bucket(bucket_name)
https://stackoverflow.com/questions/26871884/how-can-i-easily-determine-if-a-boto-3-s3-bucket-resource-exists

2020-08-10 18:39 UTC, trojikman approved these changes
Примем пока так.
Отдельно дошлю правки по докам и создам ишью

2020-08-10 18:40 UTC, trojikman commented
I approve to merge it now

2020-08-10 18:40 UTC, merged