:ambulance: replace placeholder
itpp-labs/misc-addons pull request #990
Opened 2020-05-20 23:07 UTC by trojikman

solves #745

2020-05-21 08:08 UTC, yelizariev requested changes
Also, add your copyrights

2020-05-21 08:08 UTC, yelizariev commented on web_debranding/static/src/xml/web.xml
> +                placeholder="https://www.example.com/logo.png"
You can update just a single attribute https://odoo-source.com/?q=t-operation%3D%22attributes%22&i=nope&files=&excludeFiles=po%24%7Cpot%24&repos=13.0

Also, if possible, it's better to use configured value instead of hardcoded one (``web_debranding.new_website``)

2020-05-21 08:14 UTC, yelizariev commented on web_debranding/static/src/xml/web.xml
> +                placeholder="https://www.example.com/logo.png"
At least add a TODO about web_debranding.new_website (in 13 branch is enough)

2020-05-21 15:44 UTC, trojikman commented on web_debranding/static/src/xml/web.xml
> +                placeholder="https://www.example.com/logo.png"
I made a fix for 13 too but didn't send it.

2020-05-21 15:47 UTC, trojikman commented on web_debranding/static/src/xml/web.xml
> +                placeholder="https://www.example.com/logo.png"
> You can update just a single attribute https://odoo-source.com/?q=t-operation%3D%22attributes%22&i=nope&files=&excludeFiles=po%24%7Cpot%24&repos=13.0
> 
> Also, if possible, it's better to use configured value instead of hardcoded one (`web_debranding.new_website`)

Yes, I understand that it would be better but I decided to send quick fix without spending a lot of time

2020-05-22 10:55 UTC, yelizariev approved these changes

2020-05-22 13:57 UTC, trojikman commented
I approve to merge it now

2020-05-22 13:57 UTC, merged